osql.exe -S FTOSBUCLP91\SQLEXPRESS -E -d master -Q "ALTER DATABASE MainDb SET SINGLE_USER WITH ROLLBACK IMMEDIATE"
osql.exe -S FTOSBUCLP91\SQLEXPRESS -E -d master -Q "RESTORE DATABASE MainDb FROM DISK ='C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\Backup\latestGold.bak' WITH REPLACE"
osql.exe -S FTOSBUCLP91\SQLEXPRESS -E -d master -Q "ALTER DATABASE MainDb SET MULTI_USER WITH ROLLBACK IMMEDIATE"
iisreset /restart