module.exports = {
  fields: {
    subjectToApprovalSearchBoxField: 'ebsContainerContent',
    recordNameField: '#ebsContainerContent_Name',
    approvalErrorField: locate('textarea').withAttr({ role: 'textbox' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_approvalError' })),
  },
  buttons: {
    rejectButton: '#buttonRejectId',
    approveButton: '#buttonApproveId',
    needMoreInfoButton: '#buttonNeedMoreInfoId',
    showMoreDetails: '#showMoreDetails',
    businessTransactionButton: '#HistoryBtn',
    recordFinishButton: locate('button').withText('Finish').inside('#ebsContainerContent'),
    sendToApprovalButton: locate('a').withText('Send to Accepted').inside(locate('div').withAttr({ class: 'next-status' })),
    currentStatus: locate('span').withText('Accepted').inside(locate('div').withAttr({ class: 'current-status' })),
  },
  locate: {
    locateTable: '#ebsContainerContent',
    locateRelatedTable: locate('div').withAttr({ class: 'dx-datagrid-content' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_approvalTask_filteredByEntityBWTransition_wrap' })),
    locateTransitionTable: locate('div').withAttr({ class: 'dx-datagrid-content' }).inside(locate('div').withAttr({ id: 'ebsContainerContent' })),
    currentRecordBusinessStatus: locate('div').withAttr({ class: 'current-status' }),
    approvalTaskResults: locate('div').withAttr({ id: 'ebsContainerContent' }),
    relatedApprovalTaskResults: locate('div').withAttr({ id: 'ebsContainerContent_approvalTask_filteredByEntityBWTransition_wrap' }),
    approvalTasksTaskStatus: 'status-Value',
    approvalTasksMessageTransition: 'Message_Transition_Was',
    approvalTasksApprovalDecision: 'approvalDecision-Value',
    approvalTasksApprovalUser: 'approverUserId-Value',
    rejectTaskCancelled: 'Message_Task_Cancelled',
    scriptSuccessCheckbox: locate('div').withAttr({ 'aria-checked': 'true' }),
    scriptFailCheckbox: locate('div').withAttr({ 'aria-checked': 'false' }),
    subjectToApprovalSearchBoxField: locate('input').withAttr({ class: 'dx-texteditor-input' }),
    tableLoadingAnimationVisible: locate('div').withAttr({ class: 'dx-overlay dx-widget dx-visibility-change-handler dx-loadpanel' }),
    tableLoadingAnimationInvisible: locate('div').withAttr({ class: 'dx-overlay dx-widget dx-visibility-change-handler dx-loadpanel dx-state-invisible' }),
    insertButton: locate('a').withAttr({ id: 'InsertBtn' }),
  },
};
