module.exports = {
  fields: {
    inputForAtEntityDefaultTextAtt: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_att_text' })),
    inputForAtEntityDefaultTextAreaAtt: locate('textarea').withAttr({ role: 'textbox' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_att_text_area' })),
    inputFieldNameEntityTextArea: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_AT_EntityDefaultTextAreaAtt_01' })),
    precision: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_precision' })),
    inputForAtEntityDefaultNumericAtt: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_att_numeric' })),
    inputFieldNameNumericEntity: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_AT_EntityDefaultNumeric_01' })),
    inputForAtEntityDefaultWholeNumberAtt: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_att_whole_number' })),
    inputFieldNameEntityWholeNumber: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_AT_EntityDefaultWholeNumber_01' })),
    inputFieldNameEntity: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_AT_EntityDefaultTextAtt_01' })),
    attributeNameField: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_name' })),
    ebsContainerContent_AT_EntityDefaultTextAtt_01attributeDisplayNameField: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_displayName' })),
    tableColumnName: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_tableColumnName' })),
    lengthField: '//*[@id="ebsContainerContent_length"]/div/div[1]/input',
    precisionField: '#ebsContainerContent_precision div input',
    notRequiredAttribute: '#ebsContainerContent_autotest_None div input',
    requiredAttribute: '#ebsContainerContent_autotest_Required div input',
    recommendedAttribute: '#ebsContainerContent_autotest_Recommended div input',
    readOnlyAttribute: '.dx-state-readonly',
    requiredField: '.ebs-required',
    recommendedField: '.dx-recomanded',
    attributeSearch: '//*[@id="ebsContainerContent_sys_entity_sys_attribute_entityView"]/div/div[5]/div/table/tbody/tr[2]/td[2]/div/div[2]/div/div/input',
    attributeResultsFound: '//*[@id="ebsContainerContent_sys_entity_sys_attribute_entityView"]/div/div[6]/div/table/tbody/tr[2]/td[3]',
    lookupEntityNameField: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_lookupToEntityName_popupLkp_lookupgrid' })),
    addLookupAttributeTable: locate('div').withAttr({ id: 'ebsContainerContent_lookupToEntityName_popupLkp_lookupgrid' }),
    relationshiptableName: 'div#ebsContainerContent > div:nth-of-type(5) > div > h4',
    relationshipTableNoDataField: 'div#ebsContainerContent_AT_InsIns1_AT_InsIns2 > div > div:nth-of-type(6) > span',
    relationshipInsertExistingTableNoDataField: 'div#ebsContainerContent_AT_InsIns1_AT_InsIns2_manyPopup_lookupgrid > div > div:nth-of-type(6) > span',
    relationshipInsertExistingAt_RemoveEx1_At_RemoveEx2TableNoDataField: 'div#ebsContainerContent_AT_RemoveEx1_AT_RemoveEx2 > div > div:nth-of-type(6) > span',
    searchForProductInsertExistingAttributeField: '//*[@id="ebsContainerContent_AT_InsertEx1_AT_InsertEx2_manyPopup_lookupgrid"]/div[1]/div[5]/div[1]/table[1]/tbody[1]/tr[2]/td[2]/div[1]/div[2]/div[1]/div[1]/div[1]/input[1]',
    nameOfProductInsertExistingField: '//*[@id="ebsContainerContent_AT_InsertEx1_AT_InsertEx2_manyPopup_lookupgrid"]/div[1]/div[6]/div[1]/div[1]/div[1]/div[1]/table[1]/tbody[1]/tr[1]/td[2]',
    searchEditAttributeInsertExistingField: '//*[@id="ebsContainerContent_AT_InsertEx1_AT_InsertEx2"]/div[1]/div[5]/div[1]/table[1]/tbody[1]/tr[2]/td[2]/div[1]/div[2]/div[1]/div[1]/div[1]/input[1]',
    searchForProductInsertInsertExistingAttributeField: '//*[@id="ebsContainerContent_AT_InsIns1_AT_InsIns2"]/div[1]/div[5]/div[1]/table[1]/tbody[1]/tr[2]/td[2]/div[1]/div[2]/div[1]/div[1]/div[1]/input[1]',
    searchForRemoveProductExistingField: '//*[@id="ebsContainerContent_AT_RemoveEx1_AT_RemoveEx2"]/div[1]/div[5]/div[1]/table[1]/tbody[1]/tr[2]/td[2]/div[1]/div[2]/div[1]/div[1]/div[1]/input[1]',
    tableRowValueFromEditAttributeInsertExistingField: '#ebsContainerContent_AT_InsertEx1_AT_InsertEx2 .dx-datagrid-rowsview table tr > td:nth-child(2)',
    tableRowValueProductEditAttributeInsertExistingField: '#ebsContainerContent_AT_InsertEx1_AT_InsertEx2_manyPopup_lookupgrid .dx-datagrid-rowsview table tr > td:nth-child(2)',
    tableRowValueProductEditAttributeInsertInsertExistingField: '#ebsContainerContent_AT_InsIns1_AT_InsIns2_manyPopup_lookupgrid .dx-datagrid-rowsview table tr > td:nth-child(2)',
    tableRowValueFrom_AT_RemoveEx1_AT_RemoveEx2EditAttributeInsertExistingField: '#ebsContainerContent_AT_RemoveEx1_AT_RemoveEx2 .dx-datagrid-rowsview table tr > td:nth-child(2)',
    dataAlreadyExistsErrorMessageField: '.jq-icon-error',
    parent_AT_1toNParentEntIdField: 'div#ebsContainerContent_AT_1toNParentEntId_textBox > div > div > input',
    name_AT_1toNParentEntIdField: 'div#ebsContainerContent_Name > div > div > input',
    childNameAT_1toNParentEntField: 'div#ebsContainerContent_AT_1toNChildEnt_AT_1toNParentEntId_AT_1toNParentEnt > div > div:nth-of-type(6) > div > table > tbody > tr > td:nth-of-type(2)',
    selectFirstRecordFromTableParent2Popup: 'div#ebsContainerContent_AT_1toNParentEntId_popupLkp_lookupgrid > div > div:nth-of-type(6) > div > div > div > div > table > tbody > tr > td',
    searchParentAT_1toNParentEntId_popupField: 'div#ebsContainerContent_AT_1toNParentEntId_popupLkp_lookupgrid > div > div:nth-of-type(5) > div > table > tbody > tr:nth-of-type(2) > td > div > div:nth-of-type(2) > div > div > div > input',
    noDataTableAT_1toNChildEnt_AT_1toNParentEntField: 'div#ebsContainerContent_AT_1toNChildEnt_AT_1toNParentEntId_AT_1toNParentEnt > div > div:nth-of-type(6) > span',
    resultForNoData: '.dx-datagrid-nodata',
    searchResultAttribute_AT_CreateRelCascade1_AT_CreateRelCascade2Field: 'div#ebsContainerContent_AT_CreateRelCascade1_AT_CreateRelCascade2Id_AT_CreateRelCascade2 > div > div:nth-of-type(5) > div > table > tbody > tr:nth-of-type(2) > td:nth-of-type(2) > div > div:nth-of-type(2) > div > div > div > input',
    searchResultAttribute_AT_CreateRelRestricted1_AT_CreateRelRestricted2Field: 'div#ebsContainerContent_AT_CreateRelRestricted1_AT_CreateRelRestricted2Id_AT_CreateRelRestricted2 > div > div:nth-of-type(5) > div > table > tbody > tr:nth-of-type(2) > td:nth-of-type(2) > div > div:nth-of-type(2) > div > div > div > input',
    tableRowValueFrom_AT_CreateRelCascade1_AT_CreateRelCascade2IdwField: 'div#ebsContainerContent_AT_CreateRelCascade1_AT_CreateRelCascade2Id_AT_CreateRelCascade2 > div > div:nth-of-type(6) > div > table > tbody > tr > td:nth-of-type(2)',
    tableRowValueFrom_AT_CreateRelRestricted1_AT_CreateRelRestricted2Field: 'div#ebsContainerContent_AT_CreateRelRestricted1_AT_CreateRelRestricted2Id_AT_CreateRelRestricted2 > div > div:nth-of-type(6) > div > table > tbody > tr > td:nth-of-type(2)',
    nameNewChild_AT_CreateRelCascade1Field: '#ebsContainerContent_Name .dx-texteditor-input',
    dataRecordInsertedSuccessField: '.jq-toast-single jq-has-icon jq-icon-success',
    noDataField: '.dx-datagrid-nodata',
    constrRelshipRestrictedUpdateParent: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_Name' })),
    parentUpdatedInputField: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_AT_CreateRelRestricted2Id_textBox' })),
    lookupUpdatedReadonlyFieldEditDltLookup: locate('input').withAttr({ type: 'text' }).withAttr({ 'aria-readonly': 'true' }).inside(locate('#ebsContainerContent_AT_EntForEditLkpId_textBox')),
    virtualAttrSearchField: locate('input').withAttr({ type: 'text' }).inside(locate('td').withAttr({ 'aria-label': 'Column Display Name, Filter cell' })),
    requiredLevelAttributeField: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_fieldRequiredLevelId_list' })),
    inputLookupRelationshipName: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_lookupRelationshipName' })),
    inputAttributeName: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_Name' })),
    inputAttributeLookupField: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_AT_LkpAttrEntId_Required_textBox' })),
    defaultValue: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_defaultValue' })),
    attributeDisplayNameField: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_displayName' })),
    defaultValueForTextArea: locate('textarea').withAttr({ role: 'textbox' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_defaultValue' })),
    idDefaultValue: '#ebsContainerContent_defaultValue',
    scrollAttType: locate('div').withAttr({ role: 'option' }).inside(locate('div').withAttr({ role: 'listbox' })),
  },
  buttons: {
    isRequired: '#ebsContainerContent_isReadonly',
    isIdentity: '#ebsContainerContent_isIdentity',
    lookupToEntityDropdown: '#ebsContainerContent_lookupToEntityName_button',
    insertInsertExistingButton: '#ebsContainerContent_AT_InsIns1_AT_InsIns2_manyPopup_lookupgrid_toolbar_item_3',
    okInsertExistingButton: '#ebsContainerContent_AT_InsertEx1_AT_InsertEx2_manyPopup_lookupgrid_toolbar_item_4',
    removeExisting_AT_RemoveEx1_AT_RemoveEx2_RelationshipButton: '#ebsContainerContent_AT_RemoveEx1_AT_RemoveEx2_toolbar_item_2',
    insertExistingButton: '#ebsContainerContent_AT_InsertEx1_AT_InsertEx2_toolbar_item_1',
    insertExistingButton_AT_CheckRelConfig2_AT_CheckRelConfig1_Button: 'div#ebsContainerContent_AT_CheckRelConfig2_AT_CheckRelConfig1_insert_toolbar_item_1',
    okInsert_AT_CheckRelConfig2_AT_CheckRelConfig1_ViewPopup_Button: '#ebsContainerContent_AT_CheckRelConfig2_AT_CheckRelConfig1_insert_manyPopup_lookupgrid_toolbar_item_4',
    insertExisting_AT_CheckRelConfig2_AT_CheckRelConfig1_Button: '#ebsContainerContent_AT_CheckRelConfig2_AT_CheckRelConfig1_toolbar_item_1',
    okPopupAT_CheckRelConfig2_AT_CheckRelConfig1Button: '#ebsContainerContent_AT_CheckRelConfig2_AT_CheckRelConfig1_manyPopup_lookupgrid_toolbar_item_3',
    insert_AT_1toNChildEnt_AT_1toNParentEntId_AT_1toNParentEnt_Button: 'div#ebsContainerContent_AT_1toNChildEnt_AT_1toNParentEntId_AT_1toNParentEnt_toolbar_item_1',
    okPopupParentAT_1toNParentEntButton: 'div#ebsContainerContent_AT_1toNParentEntId_popupLkp_lookupgrid_toolbar_item_4',
    deleteAT_1toNChildEnt_AT_1toNParentEntButton: '#ebsContainerContent_AT_1toNChildEnt_AT_1toNParentEntId_AT_1toNParentEnt_toolbar_item_2',
    insertNewChild_AT_CreateRelCascade1_AT_CreateRelCascade2Button: '#ebsContainerContent_AT_CreateRelCascade1_AT_CreateRelCascade2Id_AT_CreateRelCascade2_toolbar_item_1',
    insertNewChild_AT_CreateRelRestricted1_AT_CreateRelRestricted2Button: '#ebsContainerContent_AT_CreateRelRestricted1_AT_CreateRelRestricted2Id_AT_CreateRelRestricted2_toolbar_item_1',
    okVirtualAttribute: '#ebsContainerContent_virtualAttributeId_popupLkp_lookupgrid_toolbar_item_3',
    okAttribute: '#ebsContainerContent_attributeId_popupLkp_lookupgrid_toolbar_item_3',
    lookupAttributeButton: '#ebsContainerContent_AT_LkpAttrEntId_Required_button',
    okLookupAttributeButton: '#ebsContainerContent_AT_LkpAttrEntId_Required_popupLkp_lookupgrid_toolbar_item_4',

  },
  table: {
    relationshipLookupTable: locate('div').withAttr({ id: 'ebsContainerContent_AT_LkpAttrEnt1_AT_LkpAttrEntId_Required_AT_LkpAttrEnt2' }),
    lookupLkpAttrEntIdTable: '#ebsContainerContent_AT_LkpAttrEntId_Required_popupLkp_lookupgrid',
  },
  dropdown: {
    attributeType: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_attributeTypeId_list' })),
    requiredLevel: '#ebsContainerContent_requiredLevelId_list div div div.dx-texteditor-input-container input',
    requiredLevelAttribute: locate('div').withAttr({ role: 'button' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_fieldRequiredLevelId_list' })),
  },
  container: {
    attributeContainer: '.dx-select-checkboxes-hidden',
    tableAT_CheckRelConfig2_AT_CheckRelConfig1_ViewContainer: '#ebsContainerContent_AT_CheckRelConfig2_AT_CheckRelConfig1_insert',
    tableAT_CheckRelConfig2_AT_CheckRelConfig1_ViewPopup_Container: '#ebsContainerContent_AT_CheckRelConfig2_AT_CheckRelConfig1_insert_manyPopup_lookupgrid',
    tableAT_CheckRelConfig2_AT_CheckRelConfig1_Container: '#ebsContainerContent_AT_CheckRelConfig2_AT_CheckRelConfig1',
    defaultRemove_AT_RemoveEx1_AT_RemoveEx2: '#ebsContainerContent_AT_RemoveEx1_AT_RemoveEx2',
    toolbarButtons_AT_CheckRelConfig2_AT_CheckRelConfig1_Container: '#ebsToolbar',
    name_AT_1toNParentEntFieldContainer: locate('div').withAttr({ 'data-label-for': 'ebsContainerContent_Name' }).withText('Name'),
    parent_AT_1toNParentEntFieldContainer: locate('div').withAttr({ 'data-label-for': 'ebsContainerContent_AT_1toNParentEntId' }).withText('Parent'),
    outsideContainer: 'div#ew-container > div',
    defaultEntityTableContainer: '#ebsContainerContent',
    virtualAttributeTableContainer: '#ebsContainerContent_virtualAttributeId_popupLkp_lookupgrid',
    attributePopupLKPContainer: '#ebsContainerContent_attributeId_popupLkp_lookupgrid',
    attributePopupLKPViewContainer: '#ebsContainerContent_lookupViewId_popupLkp_lookupgrid',
  },
  checkboxes: {
    firstProductFromTableCheckbox: 'div#ebsContainerContent_AT_InsertEx1_AT_InsertEx2_manyPopup_lookupgrid > div > div:nth-of-type(6) > div > div > div > div > table > tbody > tr > td > div > div > span',
    secondProductFromTableCheckbox: 'div#ebsContainerContent_AT_InsertEx1_AT_InsertEx2_manyPopup_lookupgrid > div > div:nth-of-type(6) > div > div > div > div > table > tbody > tr:nth-of-type(2) > td > div > div > span',
    selectAllRecordsFromTableCheckbox: locate('span').withAttr({ class: 'dx-checkbox-icon' }).inside(locate('div').withAttr({ class: 'dx-checkbox-container' })),
    lookupAsDropdownCheckbox: '#ebsContainerContent_lookupAsDropDown',
  },
  selector: {
    constrRelshipRecordParentFromTable: locate('td').withText('Parent').inside(locate('tr').withAttr({ 'aria-rowindex': '1' })),
    constrRelshipYesPopupButton: locate('span').withText('Yes').inside(locate('.dx-popup-content')),
  },
  link: {
    autoTestSection_AT_CheckRelConfig2_AT_CheckRelConfig1_link: '#ebsContainerContent_AT_CheckRelConfig2_AT_CheckRelConfig1_collapse',
    parent_AT_1TONCHILDENT_link: 'div#ebsContainerContent_AT_1toNParentEntId_button > div > i',
  },
  label: {
    nameLabel: locate('div').withAttr({ 'data-label-for': 'ebsContainerContent_name' }).withText('name'),
    lookupUpdatedLabel: locate('div').withAttr({ 'data-label-for': 'ebsContainerContent_AT_EntForEditLkpId' }).withText('Lookup - Updated'),
  },
};
