module.exports = {
  fields: {
    approvalRuleName: '#ebsContainerContent_name div div.dx-texteditor-input-container input',
    rejectedBWStatusLoader: '#ebsContainerContent_rejectedStateId_dataGrid div div.dx-overlay.dx-widget.dx-visibility-change-handler.dx-loadpanel div div',
    approvalTriggersNameField: '#ebsContainerContent_name div div.dx-texteditor-input-container input',
    competenceApprovalModeField: '#ebsContainerContent_competenceApprovalMode_list',
    triggersValidationModeField: '#ebsContainerContent_ruleExecutionMode_list',
    requiredEvaluationValueField: '#ebsContainerContent_requiredEvaluationValue_list',
    triggersValidationModeTextField: '#ebsContainerContent_ruleExecutionMode_list div.dx-dropdowneditor-input-wrapper.dx-selectbox-container div div.dx-texteditor-input-container input',
    competenceModeAll: locate('p').withAttr({ title: 'All' }),
    approvalResults: locate('div').withAttr({ id: 'ebsContainerContent_entityBWTransitionApproval_entityBWTransitionId_entityBWTransition' }),
  },
  buttons: {
    insertApprovalsButton: '#ebsContainerContent_entityBWTransitionApproval_entityBWTransitionId_entityBWTransition_toolbar_item_1',
    addUserCompetenceButton: locate('div').withAttr({ role: 'button' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_userCompetenceId' })),
    addRejectedStatus: '#ebsContainerContent_rejectedStateId_dropDownBox div.dx-dropdowneditor-input-wrapper div div.dx-texteditor-buttons-container div',
    addEntityFormButton: '#ebsContainerContent_entityFormId_dropDownBox div.dx-dropdowneditor-input-wrapper div div.dx-texteditor-buttons-container div',
    insertApprovalTriggersButton: locate('div').withAttr({ id: 'ebsContainerContent_approvalBusinessCondition_TransitionApprovalId_TransitionApproval_toolbar_item_1' }),
    approvalTriggersBWRuleButton: '#ebsContainerContent_entityBWRuleId_dropDownBox div.dx-dropdowneditor-input-wrapper div div.dx-texteditor-buttons-container div',
    chooseStatusButton: locate('a').withAttr({ class: 'ui dropdown' }),
    bwStatusButton: locate('a').withAttr({ class: 'btn btn-lg btn-simple' }).first(),
    bwCurrentStatus: locate('span').withAttr({ class: 'text-default' }),
    isAdvisoryButton: '#ebsContainerContent_isOptional',
    deleteApprovalTriggerButton: '#ebsContainerContent_approvalBusinessCondition_TransitionApprovalId_TransitionApproval_toolbar_item_2',
    deleteApprovalRuleButton: '#ebsContainerContent_entityBWTransitionApproval_entityBWTransitionId_entityBWTransition_toolbar_item_2',
    userCompetencePageButton: locate('div').withAttr({ 'aria-label': 'Display 20 items on page' }),
  },
  tabs: {
    approvalsTab: locate('div').withAttr({ class: 'dx-item dx-tab stepNumber-3' }),
  },
  checkbox: {
    requiresApproval: '#ebsContainerContent_requiresApproval div span',
  },
  locate: {
    rejectedStateIdLocate: '#ebsContainerContent_rejectedStateId_dataGrid',
    entityFormIdLocate: '#ebsContainerContent_entityFormId_dataGrid',
    rejectedTextLocate: '#ebsContainerContent_rejectedText',
    approvalTextLocate: '#ebsContainerContent_approvalText',
    entityBWRuleLocate: '#ebsContainerContent_entityBWRuleId_dataGrid',
    entityBWTransitionLocate: '#ebsContainerContent_entityBWTransitionApproval_entityBWTransitionId_entityBWTransition',
    approvalBCLocate: '#ebsContainerContent_approvalBusinessCondition_TransitionApprovalId_TransitionApproval',
    userCompetenceTableLocate: locate('div').withAttr({ id: 'ebsContainerContent_userCompetenceId_popupLkp_lookupgrid' }),
    approvalTriggerPage: locate('div').withAttr({ class: 'ew-form border-radius-bottom form_approvalBusinessCondition_default' }),
  },
};
