module.exports = {
  fields: {
    businessConditionsSearchField: '//*[@id="ebsContainerContent"]/div/div[5]/div/table/tbody/tr[2]/td[2]/div/div[2]/div/div/div[1]/input',
    businessConditionNameField: locate('input').withAttr({ class: 'dx-texteditor-input' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_Name' })),
    businessConditionCodeField: '//*[@id="ebsContainerContent_code"]/div/div[1]/input',
    businessConditionDescriptionField: '#ebsContainerContent_description div div.dx-texteditor-input-container textarea',
    businessConditionsSearchNameField: '//*[@id="ebsContainerContent_entityBWRule_entityBW"]/div/div[5]/div/table/tbody/tr[2]/td[2]/div/div[2]/div/div/div[1]/input',
    businessConditionResultsNameField: '//*[@id="ebsContainerContent_entityBWRule_entityBW"]/div/div[6]/div/table/tbody/tr[1]/td[2]',
    businessConditionResultsCodeField: '//*[@id="ebsContainerContent_entityBWRule_entityBW"]/div/div[6]/div/table/tbody/tr[1]/td[3]',
    businessConditionResultsDescriptionField: '//*[@id="ebsContainerContent_entityBWRule_entityBW"]/div/div[6]/div/table/tbody/tr[1]/td[4]',
    bwEntityAddName: '//*[@id="ebsContainerContent_Name"]/div/div[1]/input',
    bwChangeStatusField: locate('div').withAttr({ class: 'next-status' }).inside(locate('div').withAttr({ id: 'ebsContainer' })),
    bwCurrentStatusField: locate('div').withAttr({ class: 'current-status' }),
    bwTransitionFromStatusField: '//*[@id="ebsContainerContent"]/div/div[6]/div/table/tbody/tr[1]/td[4]',
    bwTransitionToStatusField: '//*[@id="ebsContainerContent"]/div/div[6]/div/table/tbody/tr[1]/td[5]',
    parentConditionValueTextField: '//*[@id="ebsContainerContent_rule_filter_filterBuilder"]/div/div[2]/div/div/div[4]/div/div/div/div[1]/input',
    childFirstConditionValueTextField: '//*[@id="ebsContainerContent_rule_filter_filterBuilder"]/div/div/div[2]/div[2]/div[2]/div/div/div[4]/div/div/div[1]/input',
    childFirstConditionValueTextField2: '//*[@id="Name"]',
    childSecondConditionValueTextField: '//*[@id="ebsContainerContent_rule_filter_filterBuilder"]/div/div[2]/div[2]/div[2]/div[2]/div/div[4]/div/div/div/div[1]/input',
    conditionValueTextField: '//*[@id="ebsContainerContent_rule_filter_filterBuilder"]/div/div[2]/div/div/div[4]/div/div/div[1]/input',
    secondConditionValueTextField: '//*[@id="ebsContainerContent_rule_filter_filterBuilder"]/div/div[2]/div[1]/div/div[4]/div/div/div/div[1]/input',
    bwConditionTable: locate('div').withAttr({ id: 'ebsContainerContent_entityBWRule_entityBW_wrap' }),
  },
  buttons: {
    activeBusinessWorkflowButton: locate('button').withAttr({ id: 'enableDisableButton' }),
    insertBusinessConditionButton: '#ebsContainerContent_entityBWRule_entityBW_toolbar_item_1',
    bwEntityUJNextButton: '//*[@id="ebsContainerContent"]/div[3]/div/button[2]',
    bwChangeNextStatusButton: locate('a').withText('Accepted').inside(locate('div').withAttr({ class: 'next-status' })),
    bwBusinessTransactionButton: '#HistoryBtn',
    parentAddRuleButton: '//html[@id=\'main-page\']//div[@id=\'ebsContainerContent_rule_filter_filterBuilder\']//div[@class=\'dx-filterbuilder-group-item\']/div[2]',
    childAddRuleButton: '//html[@id=\'main-page\']//div[@id=\'ebsContainerContent_rule_filter_filterBuilder\']/div[@class=\'dx-filterbuilder-group\']/div[@class=\'dx-filterbuilder-group-content\']/div[2]/div[@class=\'dx-filterbuilder-group-item\']/div[3]',
    childRuleOperatorButton: '//html[@id=\'main-page\']//div[@id=\'ebsContainerContent_rule_filter_filterBuilder\']/div[@class=\'dx-filterbuilder-group\']/div[@class=\'dx-filterbuilder-group-content\']/div[2]/div[@class=\'dx-filterbuilder-group-item\']//div[.=\'And\']',
    parentConditionTypeButton: '//html[@id=\'main-page\']//div[@id=\'ebsContainerContent_rule_filter_filterBuilder\']/div[@class=\'dx-filterbuilder-group\']//div[.=\'Checking with Custom Processor\']',
    childFirstConditionTypeButton: '//html[@id=\'main-page\']//div[@id=\'ebsContainerContent_rule_filter_filterBuilder\']/div[@class=\'dx-filterbuilder-group\']/div[@class=\'dx-filterbuilder-group-content\']/div[2]/div[@class=\'dx-filterbuilder-group-content\']//div[@class=\'dx-filterbuilder-group-item\']//div[.=\'Checking with Custom Processor\']',
    childSecondConditionTypeButton: '//html[@id=\'main-page\']//div[@id=\'ebsContainerContent_rule_filter_filterBuilder\']/div[@class=\'dx-filterbuilder-group\']/div[@class=\'dx-filterbuilder-group-content\']//div[@class=\'dx-filterbuilder-group-content\']//div[@class=\'dx-filterbuilder-group-item\']//div[.=\'Checking with Custom Processor\']',
    parentConditionOperatorButton: '//html[@id=\'main-page\']//div[@id=\'ebsContainerContent_rule_filter_filterBuilder\']/div[@class=\'dx-filterbuilder-group\']//div[.=\'Equals\']',
    childSecondConditionOperatorButton: '//html[@id=\'main-page\']//div[@id=\'ebsContainerContent_rule_filter_filterBuilder\']/div[@class=\'dx-filterbuilder-group\']/div[@class=\'dx-filterbuilder-group-content\']//div[@class=\'dx-filterbuilder-group-content\']//div[@class=\'dx-filterbuilder-group-item\']/div[.=\'Equals\']',
    parentConditionValueButton: '//html[@id=\'main-page\']//div[@id=\'ebsContainerContent_rule_filter_filterBuilder\']/div[@class=\'dx-filterbuilder-group\']//div[@class=\'dx-filterbuilder-item-value-text\']',
    secondConditionValueButton: '//html[@id=\'main-page\']//div[@id=\'ebsContainerContent_rule_filter_filterBuilder\']/div[@class=\'dx-filterbuilder-group\']/div[@class=\'dx-filterbuilder-group-content\']/div[2]/div[@class=\'dx-filterbuilder-group-item\']/div[4]/div[@class=\'dx-filterbuilder-item-value-text\']',
    childFirstConditionValueButton: '//html[@id=\'main-page\']//div[@id=\'ebsContainerContent_rule_filter_filterBuilder\']/div[@class=\'dx-filterbuilder-group\']/div[@class=\'dx-filterbuilder-group-content\']//div[@class=\'dx-filterbuilder-group-content\']//div[@class=\'dx-filterbuilder-group-item\']//div[@class=\'dx-filterbuilder-item-value-text\']',
    childSecondConditionValueButton: '//html[@id=\'main-page\']//div[@id=\'ebsContainerContent_rule_filter_filterBuilder\']/div[@class=\'dx-filterbuilder-group\']/div[@class=\'dx-filterbuilder-group-content\']//div[@class=\'dx-filterbuilder-group-content\']/div[2]/div[@class=\'dx-filterbuilder-group-item\']//div[@class=\'dx-filterbuilder-item-value-text\']',
  },
  tabs: {
    generalTab: '#stepper div div.dx-item.dx-tab.stepNumber-1',
    businessConditionsTab: '#stepper div div.dx-item.dx-tab.stepNumber-2',
  },
  selector: {
    parentAddGroupDropDownList: '//html[@id=\'main-page\']/body/div[4]/div//div[@role=\'tree\']//ul[@role=\'group\']/li[2]//span[.=\'Add Group\']',
    childRuleOperatorDropDownList: '//html[@id=\'main-page\']/body/div[4]//div[@role=\'tree\']//ul[@role=\'group\']/li[2]/div/div[@class=\'dx-item-content dx-treeview-item-content\']',
  },
  locate: {
    containerContentLocate: '#ebsContainerContent',
    entityBWRuleLocate: '#ebsContainerContent_entityBWRule_entityBW',
    bwTableInputFieldLocate: locate('input').withAttr({ class: 'dx-texteditor-input' }),
    searchResultsBusinessWorkflowLocate: locate('div').withAttr({ class: 'dx-datagrid-content' }),
  },
};
