module.exports = {
  fields: {
    nameInput: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_name'),
    chartTitleInput: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_chartTitle'),
    nameFieldInput: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_nameField'),
    valueInputField: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_valueField'),
    axisXTitleInput: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_axisXTitle'),
    axisYTitleInput: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_axisYTitle'),
    searchAfterName: locate('input').withAttr({ type: 'text' }).inside(locate('td').withAttr({ 'aria-label': 'Column Name, Filter cell' })).inside('#ebsContainerContent'),
  },
  dropdowns: {
    chartBaseType: '#ebsContainerContent_chartBaseType_list',
    chartType: '#ebsContainerContent_chartType_list',
    legendHorizontalAlignment: '#ebsContainerContent_legendHorizontalAlignment_list',
    legendVerticalAlignment: '#ebsContainerContent_legendVerticalAlignment_list',
    overrideColor: '#ebsContainerContent_overrideColor',
  },
  checkbox: {
    showLegendCheckbox: '#ebsContainerContent_showLegend',
    showLabelsCheckbox: '#ebsContainerContent_showLabels',
    showOnHomeCheckbox: locate('span').withAttr({ class: 'dx-checkbox-icon' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_showOnHome' })),
  },
  selector: {
    dropdownOption: locate('div').withAttr({ role: 'option' }),
    firstLineFetchExpressionCodeEditor: '//*[@id="ebsContainerContent_fetchExpressionmonaco"]/div/div[1]/div[2]/div[1]/div[4]/div',
    monacoCodeEditor1: '1',
    tablist: locate('ul').withAttr({ role: 'tablist' }),
    resizableWidgetDashboard: locate('div').withAttr({ class: 'ui-resizable-handle ui-resizable-se ui-icon ui-icon-gripsmall-diagonal-se' }),
  },
  chart: {
    firstColumnValue: '//*[local-name()=\'tspan\'][text() = \'100\']',
    firstColumnName: '//*[local-name()=\'text\'][text() = \'Auto1\']',
    firstColumnChart: '//*[local-name()=\'rect\'][@height=\'35\']',
    secondColumnValue: '//*[local-name()=\'tspan\'][text() = \'300\']',
    secondColumnName: '//*[local-name()=\'text\'][text() = \'Auto3\']',
    secondColumnChart: '//*[local-name()=\'rect\'][@height=\'106\']',
    thirdColumnValue: '//*[local-name()=\'tspan\'][text() = \'200\']',
    thirdColumnName: '//*[local-name()=\'text\'][text() = \'Auto2\']',
    thirdColumnChart: '//*[local-name()=\'rect\'][@height=\'70\']',
    nameAxisX: '//*[local-name()=\'text\'][text() = \'name\']',
    nameAxisY: '//*[local-name()=\'text\'][text() = \'Value\']',
    chartLegend: '//*[local-name()=\'rect\'][@class=\'highcharts-legend-box\']',
    chartEditFirstColumn: '//*[local-name()=\'rect\'][@height=\'130\' and @fill=\'rgb(255, 128, 103)\']',
    chartEditSecondColumn: '//*[local-name()=\'rect\'][@height=\'391\' and @fill=\'rgb(255, 128, 103)\']',
    chartEditThirdColumn: '//*[local-name()=\'rect\'][@height=\'261\' and @fill=\'rgb(255, 128, 103)\']',
    chartEditTitle: '//*[local-name()=\'text\'][text() = \'AT_NewChart\']',
  },
  container: {
    defaultContainer: '#ebsContainerContent',
  },
};
