module.exports = {
  fields: {
    advancedCodEditorField: locate('a').withText('Advanced Code Editor').inside(locate('li').withAttr({ class: 'leaf-menu-item found' })),
    entitiesFiltersField: locate('div').withAttr({ 'data-value': 'entities' }),
    clientScriptLibrariesFiltersField: locate('div').withAttr({ 'data-value': 'csLibraries' }),
    automationScriptsDemandFiltersField: locate('div').withAttr({ 'data-value': 'wfOnDemand' }),
    automationScriptsLibrariesFiltersField: locate('div').withAttr({ 'data-value': 'wfLibraries' }),
    customUserJourneysFiltersField: locate('div').withAttr({ 'data-value': 'customActions' }),
    htmlWidgetsFiltersField: locate('div').withAttr({ 'data-value': 'htmlWidgets' }),
    styleSheetsFiltersField: locate('div').withAttr({ 'data-value': 'styleSheets' }),
    codeBlockFiltersField: locate('div').withAttr({ 'data-value': 'codeBlock' }),
    DAEntityField: locate('span').withText('Entities').inside(locate('li.dx-treeview-node.dx-treeview-item-without-checkbox')),
    dataViewsField: locate('span').withText('Views').inside(locate('li.dx-treeview-node.dx-treeview-item-without-checkbox')),
    defaultDataViewField: locate('span').withText('default').inside(locate('li.dx-treeview-node.dx-treeview-item-without-checkbox')),
    fetchObjectExpressionField: locate('span').withText('fetchObjectExpression.js').inside(locate('li.dx-treeview-node.dx-treeview-item-without-checkbox')),
    entityNameField: locate('li.dx-treeview-node.dx-treeview-item-without-checkbox'),
    topWarningMessageField: locate('div.ftos-ce-lock-info-holder.ftos-panel-item'),
    entityField: locate('li').withAttr({ 'aria-label': 'Entities' }),
    viewField: locate('li').withAttr({ 'aria-label': 'Views' }),
  },
  buttons: {
    filterByProjectButton: locate('span').withText('Filter by project').inside(locate('button')),
    filterByDigitalAssetButton: locate('span').withText('Filter by digital asset').inside(locate('button')),
    filterByItemTypeButton: locate('span').withText('Filter by item type').inside(locate('button')),
    toggleTreeViewItemsButton: locate('div').withAttr({ class: 'dx-treeview-toggle-item-visibility' }),
    deleteReferenceDigitalAsset: '#ebsContainerContent_applicationDependency_applicationId_application_default_toolbar_item_2',
    deselectAllDigitalAssetsButton: locate('span').withText('Deselect all digital assets'),
    deselectAllItemTypesButton: locate('span').withText('Deselect all item types'),
    addNewStyleSheetButtonCodeEditor: locate('li').withAttr({ 'aria-label': 'Add new Style Sheet' }),
    searchMenuItemButton: locate('i').withAttr({ class: 'pe-7s-search dsg-home-search-icon' }).inside('#searchMenuHolder'),
    filtersButton: locate('span').withText('Filter by item type').inside(locate('button').withAttr({ class: 'btn btn-default btn-sm dropdown-toggle' })),
    deselectAllProjectsButton: locate('span').withText('Deselect all projects'),
    openEntitiesItemsButton: locate('div').withAttr({ class: 'dx-treeview-toggle-item-visibility' }).inside(locate('li').withAttr({ 'aria-label': 'Entities' })),
    independentItemsButton: locate('div').withAttr({ class: 'dx-treeview-toggle-item-visibility' }).inside(locate('li').withAttr({ 'aria-label': 'Independent Items' })),
    selectAllItemTypesButton: locate('span').withText('Select all item-types'),
    filterByProjectsButton: locate('span').withText('Filter by project').inside(locate('button').withAttr({ class: 'btn btn-default btn-sm dropdown-toggle' })),
    filterByDAButton: locate('span').withText('Filter by digital asset').inside(locate('button').withAttr({ class: 'btn btn-default btn-sm dropdown-toggle' })),
    independentItemsFromFilterByDAButton: locate('span').withText('Independent Items').inside(locate('div').withAttr({ class: 'dropdown-item checkbox checkbox-sm checkbox-color1' })),
    deselectAllApplicationsButton: locate('span').withText('Deselect all digital assets').inside(locate('div').withAttr({ class: 'dropdown-item checkbox checkbox-sm checkbox-color1' })),
    selectAllApplicationsButton: locate('span').withText('Select all digital assets').inside(locate('div').withAttr({ class: 'dropdown-item checkbox checkbox-sm checkbox-color1' })),
    arrowOpenDAButton: locate('div').withAttr({class: 'dx-treeview-toggle-item-visibility'}),
    arrowCloseDAButton: locate('div').withAttr({class:'dx-treeview-toggle-item-visibility dx-treeview-toggle-item-visibility-opened'}),
    closeEntitiesItemsButton: locate('div').withAttr({ class: 'dx-treeview-toggle-item-visibility dx-treeview-toggle-item-visibility-opened' }).inside(locate('li').withAttr({ 'aria-label': 'Entities' })),
  },
  containers: {
    filterContainer: '#ebsContainer > div.main-container.with-sidebar > div > div.ftos-pnl-not-right.ftos-panel-item.ftos-panel-wrap > div.ftos-pnl-left.ftos-panel-item.ftos-panel-wrap > div.ftos-pnl-middle-left.ftos-panel-item > div > div > div > div > div > div.dx-scrollable-content > ul',
  },
  checkbox: {
    entityCheckbox: '#ebsContainer > div.main-container.with-sidebar > div > div.ftos-pnl-not-right.ftos-panel-item.ftos-panel-wrap > div.ftos-pnl-left.ftos-panel-item.ftos-panel-wrap > div.ftos-pnl-top-left.filters.ftos-panel-item > div.ftos-filters.items-filter > div > div > div:nth-child(3) > label > input[type=checkbox]',
    csLibrariesCheckbox: '#ebsContainer > div.main-container.with-sidebar > div > div.ftos-pnl-not-right.ftos-panel-item.ftos-panel-wrap > div.ftos-pnl-left.ftos-panel-item.ftos-panel-wrap > div.ftos-pnl-top-left.filters.ftos-panel-item > div.ftos-filters.items-filter > div > div > div:nth-child(4) > label > input[type=checkbox]',
    wfOnDemandCheckbox: '#ebsContainer > div.main-container.with-sidebar > div > div.ftos-pnl-not-right.ftos-panel-item.ftos-panel-wrap > div.ftos-pnl-left.ftos-panel-item.ftos-panel-wrap > div.ftos-pnl-top-left.filters.ftos-panel-item > div.ftos-filters.items-filter > div > div > div:nth-child(5) > label > input[type=checkbox]',
    wfLibrariesCheckbox: '#ebsContainer > div.main-container.with-sidebar > div > div.ftos-pnl-not-right.ftos-panel-item.ftos-panel-wrap > div.ftos-pnl-left.ftos-panel-item.ftos-panel-wrap > div.ftos-pnl-top-left.filters.ftos-panel-item > div.ftos-filters.items-filter > div > div > div:nth-child(6) > label > input[type=checkbox]',
    customActionsCheckbox: '#ebsContainer > div.main-container.with-sidebar > div > div.ftos-pnl-not-right.ftos-panel-item.ftos-panel-wrap > div.ftos-pnl-left.ftos-panel-item.ftos-panel-wrap > div.ftos-pnl-top-left.filters.ftos-panel-item > div.ftos-filters.items-filter > div > div > div:nth-child(7) > label > input[type=checkbox]',
    htmlWidgetsCheckbox: '#ebsContainer > div.main-container.with-sidebar > div > div.ftos-pnl-not-right.ftos-panel-item.ftos-panel-wrap > div.ftos-pnl-left.ftos-panel-item.ftos-panel-wrap > div.ftos-pnl-top-left.filters.ftos-panel-item > div.ftos-filters.items-filter > div > div > div:nth-child(8) > label > input[type=checkbox]',
    styleSheetsCheckbox: '#ebsContainer > div.main-container.with-sidebar > div > div.ftos-pnl-not-right.ftos-panel-item.ftos-panel-wrap > div.ftos-pnl-left.ftos-panel-item.ftos-panel-wrap > div.ftos-pnl-top-left.filters.ftos-panel-item > div.ftos-filters.items-filter > div > div > div:nth-child(9) > label > input[type=checkbox]',
    codeBlockCheckbox: '#ebsContainer > div.main-container.with-sidebar > div > div.ftos-pnl-not-right.ftos-panel-item.ftos-panel-wrap > div.ftos-pnl-left.ftos-panel-item.ftos-panel-wrap > div.ftos-pnl-top-left.filters.ftos-panel-item > div.ftos-filters.items-filter > div > div > div:nth-child(10) > label > input[type=checkbox]',
    projectCheckbox: '#ebsContainer > div.main-container.with-sidebar > div > div.ftos-pnl-not-right.ftos-panel-item.ftos-panel-wrap > div.ftos-pnl-left.ftos-panel-item.ftos-panel-wrap > div.ftos-pnl-top-left.filters.ftos-panel-item > div.ftos-filters.projects-filter > div > div > div:nth-child(4) > label > input[type=checkbox]',
    DA1Checkbox: '#ebsContainer > div.main-container.with-sidebar > div > div.ftos-pnl-not-right.ftos-panel-item.ftos-panel-wrap > div.ftos-pnl-left.ftos-panel-item.ftos-panel-wrap > div.ftos-pnl-top-left.filters.ftos-panel-item > div.ftos-filters.apps-filter > div > div > div:nth-child(14) > label > input[type=checkbox]',
    DA2Checkbox: '#ebsContainer > div.main-container.with-sidebar > div > div.ftos-pnl-not-right.ftos-panel-item.ftos-panel-wrap > div.ftos-pnl-left.ftos-panel-item.ftos-panel-wrap > div.ftos-pnl-top-left.filters.ftos-panel-item > div.ftos-filters.apps-filter > div > div > div:nth-child(15) > label > input[type=checkbox]',
  },
  selector: {
    entitiesCodeEditorOption: locate('li').withAttr({ 'aria-label': 'Entities' }),
    thirdLevelCodeEditorOption: locate('li').withAttr({ 'aria-level': '3' }),
    secondLevelCodeEditorOption: locate('li').withAttr({ 'aria-level': '2' }),
    codeEditorRightHandPanelHolder: locate('div').withAttr({ class: 'ftos-ce-props-holder' }),
    filterByOptionsCodeEditor: locate('div').withAttr({ class: 'dropdown-item checkbox checkbox-sm checkbox-color1' }),
    expandItemTreeButton: locate('div').withAttr({ class: 'dx-treeview-toggle-item-visibility' }),
    filterByDAClass: locate('div').withAttr({ class: 'dropdown-item checkbox checkbox-sm checkbox-color1' }),
  },
};
