module.exports = {
  fields: {
    nameField: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_Name'),
    infoColorInputField: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_InfoColor'),
    warningColorInputField: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_WarningColor'),
    successColorInputField: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_SuccessColor'),
    errorColorValueInputField: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_ErrorColor'),
    paletteFirstColorInputField: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_PaletteFirstColor'),
    paletteSecondColorInputField: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_PaletteSecondColor'),
    paletteThirdColorInputField: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_PaletteThirdColor'),
    entityTypeField: '#ebsContainerContent_type_list',
    businessEntityField: '#ebsContainerContent_entityId_dropDownBox',
    searchNameInputField: locate('input').withAttr({ type: 'text' }).inside(locate('td').withAttr({ 'aria-label': 'Column Name, Filter cell' })).inside('#ebsContainerContent_entityId_dataGrid'),
    searchNameMenuItem: locate('input').withAttr({ type: 'text' }).inside(locate('td').withAttr({ 'aria-label': 'Filter cell' })).inside('#ebsContainerContent_entityId_dataGrid'),
    iconURLField: '#ebsContainerContent_iconUrl',
    menuSearchInputFieldPortal: locate('input').withAttr({ type: 'text'}).inside(locate('nav').withAttr({ class: 'menu-side block-width-5' })),
    searchDisplayNameMenuItemInputField: locate('input').withAttr({ type: 'text' }).inside(locate('td').withAttr({ 'aria-label': 'Filter cell' })).inside('#ebsContainerContent'),
  },
  buttons: {
    baseThemeDropdown: '#ebsContainerContent_BaseTheme_list',
    infoColorDropdown: '#ebsContainerContent_InfoColor',
    fontsPopUpButton: '#ebsContainerContent_CustomFont_button',
    fontsOkButton: '#ebsContainerContent_CustomFont_popupLkp_lookupgrid_toolbar_item_4',
    deleteButton: '#DeleteBtn',
    iconClassButton: locate('button').withAttr({ 'aria-haspopup': 'true' }),
    menuButtonPortal: locate('a').withAttr({ id: 'ebs-context-menu' }),
    pinToHomePortalButton: locate('a').withAttr({ 'data-key-title': 'Main_Menu_Pin_List_To_Home' }),
    pinListToHomePortalButton: locate('a').withAttr({ 'title': 'Pin \'List\' to Home' }),
  },
  selectors: {
    tabList: locate('div').withAttr({ id: 'stepper' }),
    iconClassDropdown: locate('ul').withAttr({ class: 'dropdown-menu show' }),
    secondRow: locate('tr').withAttr({ 'aria-rowindex': '2' }),
  },
  errors: {
    info: locate('div').withText('TestMessage1').inside(locate('div').withAttr({ class: 'jq-toast-wrap bottom-center' })),
    success: locate('div').withText('TestMessage2').inside(locate('div').withAttr({ class: 'jq-toast-wrap bottom-center' })),
    warning: locate('div').withText('TestMessage3').inside(locate('div').withAttr({ class: 'jq-toast-wrap bottom-center' })),
    error: locate('div').withText('TestMessage4').inside(locate('div').withAttr({ class: 'jq-toast-wrap bottom-center' })),
  },
  container: {
    titleContainer: locate('div').withAttr({ class: 'ew-form-title border-radius-top block-height-4rem block-line-height-4rem block-pink' }),
    defaultContainer: '#ebsContainerContent',
  },
};
