module.exports = {
  fields: {
    nameInputField: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_name'),
    codeInputField: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_code'),
    descriptionInputField: locate('textarea').withAttr({ role: 'textbox' }).inside('#ebsContainerContent_description'),
    searchByNameInputFieldMinPlatformVersion: locate('input').withAttr({ type: 'text' }).inside(locate('td').withAttr({ 'aria-colindex': '1' })).inside('#ebsContainerContent_minPlatformVersion_popupLkp_lookupgrid'),
    searchByDisplayNameInputField: locate('input').withAttr({ type: 'text' }).inside(locate('td').withAttr({ 'aria-label': 'Column Display Name, Filter cell' })),
    codeField: '#ebsContainerContent_code',
    nameField: '#ebsContainerContent_name',
    descriptionField: '#ebsContainerContent_description',
    typeField: '#ebsContainerContent_type_dropDownBox',
    versionField: '#ebsContainerContent_version',
    creationModeList: '#ebsContainerContent_creationMode',
    statusListField: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_status_list'),
    statusInputField: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_status'),
    versionInputField: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_version'),
    searchByNameInputField: locate('input').withAttr({ type: 'text' }).inside(locate('td').withAttr({ 'aria-colindex': '2' })),
    searchByNameDAInputApplicationField: locate('input').withAttr({ type: 'text' }).inside(locate('td').withAttr({ 'aria-colindex': '1' })),
    typeCIField: '#typeCtrl',
    searchConfigItemsTypeField: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'typeCtrl' })),
    minimumPlatformVersionField: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_minPlatformVersion_textBox' })),
    inputFieldReadOnly: locate('input').withAttr({ 'aria-readonly': 'true' }),
    textareaFieldReadOnly: locate('textarea').withAttr({ 'aria-readonly': 'true' }),
    textareaFieldReadOnlyFalse: locate('textarea').withAttr({ 'aria-readonly': 'false' }),
    statusField: '#ebsContainerContent_status',
    creationModeField: '#ebsContainerContent_creationMode',
    displayNameBusinessEntityWithDA: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_displayName' })),
    entityNameField: locate('div').withText('Entity Name'),
    recordNameField: locate('div').withText('Record Name'),
    parentNameField: locate('div').withText('Parent Name'),
    digitalAssetField: locate('div').withText('Digital Asset'),
    entityField: locate('div').withText('Entity'),
    recordField: locate('div').withText('Record'),
    isMigratedField: locate('div').withText('Is Migrated'),
    deploymentPackageField: locate('div').withText('Deployment Package'),
    existingDAField: locate('div').withText('Existing Digital Asset'),
    daEditDataImportTemplateField: locate('td').withText('AT_DA_EditDataImportTemplate').inside(locate('tr').withAttr({ 'aria-rowindex': '1' })).inside('#ebsContainerContent'),
    dataImportForEditField: locate('td').withText('AT_EditDataImportTemplate').inside(locate('tr').withAttr({ 'aria-rowindex': '1' })).inside('#ebsContainerContent_applicationDataImport_applicationId_application_forApplication'),
    basedDataImportTemplatesField: locate('p').withText('Based On Data Import Templates').inside(locate('div').withAttr({ role: 'option' })).inside(locate('div').withAttr({ role: 'listbox' })),
    basedDataConfigDefinitionField: locate('p').withText('Based On Data Config Definition').inside(locate('div').withAttr({ role: 'option' })).inside(locate('div').withAttr({ role: 'listbox' })),
    daEditDataConfigDefinitionField: locate('td').withText('AT_DA_EditDataConfigDefinition').inside(locate('tr').withAttr({ 'aria-rowindex': '1' })).inside('#ebsContainerContent'),
    dataConfigForEditField: locate('td').withText('AT_EditDataConfigDefinition').inside(locate('tr').withAttr({ 'aria-rowindex': '1' })).inside('#ebsContainerContent_applicationDataImport_applicationId_application_forApplication'),
    noneDataImportField: locate('p').withText('[none]').inside(locate('div').withAttr({ role: 'option' })).inside(locate('div').withAttr({ role: 'listbox' })),
    statusLockedReadOnlyField: locate('input').withAttr({ 'aria-readonly': 'true' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_status_list' })),
    searchMenuItemField: '#mainMenuSearchInput',
  },
  buttons: {
    createNewDigitalAssetButton: locate('a').withText('Create New Digital Asset'),
    minimumPlatformVersionLookupButton: '#ebsContainerContent_minPlatformVersion_button',
    okButtonMinimumPlatformVersionLookupContainer: '#ebsContainerContent_minPlatformVersion_popupLkp_lookupgrid_toolbar_item_4',
    chooseDPForMigrationLookupButton: '#ebsContainerContent_customizationSetId_button',
    okButtonDpMigrationLookup: '#ebsContainerContent_customizationSetId_popupLkp_lookupgrid_toolbar_item_3',
    migrateButton: '#migrationBtn',
    skipWelcomeToStudioButton: locate('a').withText('Skip'),
    setAsContextDigitalAssetButton: '#setAsContextAppId',
    lockDigitalAssetButton: '#lockButton',
    unlockDigitalAssetButton: '#unlockButton',
    closeDigitalAssetButton: locate('button').withAttr({ onclick: 'ebs.closeDigitalAsset()' }),
    configurationItemButtonInfoContainer: '#digitalAssetInfoContainer_configurationItems',
    addConfigurationItemButton: '#createStandardAppCIBtn',
    branchDigitalAssetButton: '#branchApplication',
    removeConfigurationItemButton: '#deleteStandardAppCIBtn',
    saveBranchDigitalAssetButton: '#saveButton',
    insertCIData: '#CIDataGridContainer_toolbar_item_1',
    openDigitalAsset: locate('a').withText('Open Digital Asset'),
    insertNewConfigItemButton: '#CIDataGridContainer_toolbar_item_1',
    insertButtonForCiItems2: '#CIDataGridContainer_toolbar_item_1',
    insertButtonDependenciesForDigitalAsset: '#ebsContainerContent_applicationDependency_applicationId_application_default_toolbar_item_1',
    buttonForReferencedDigitalAsset: '#ebsContainerContent_refApplicationId_button',
    okButtonForReferencedDigitalAsset: '#ebsContainerContent_refApplicationId_popupLkp_lookupgrid_toolbar_item_3',
    exportCIMigrationButton: '#applicationMigration_toolbar_item_1',
    okDataImportTemplateButton: '#ebsContainerContent_dataImportId_popupLkp_lookupgrid_toolbar_item_4',
    closeImportedFileButton: locate('a').withAttr({ class: 'remove-file-btn' }).inside('#ebsContainerContent_importFile_textBox'),
    insertDataImportTemplateButton: '#ebsContainerContent_dataImportId_button',
    deleteDataImportFilesButton: '#ebsContainerContent_applicationDataImport_applicationId_application_forApplication_toolbar_item_2',
    cancelButton: locate('span').withText('Cancel').inside(locate('div').withAttr({ 'aria-label': 'Cancel' })),
    yesButton: locate('span').withText('Yes').inside(locate('div').withAttr({ 'aria-label': 'Yes' })),
    insertDataImportFilesButton: '#ebsContainerContent_applicationDataImport_applicationId_application_forApplication_toolbar_item_1',
    okDataConfigDefinitionButton: '#ebsContainerContent_dataConfigDefinitionId_popupLkp_lookupgrid_toolbar_item_4',
    insertDataConfigDefinitionButton: '#ebsContainerContent_dataConfigDefinitionId_button',
    filterByProjectButton: locate('span').withText('Filter by project').inside(locate('button')),
    filterByDigitalAssetButton: locate('span').withText('Filter by digital asset').inside(locate('button')),
    filterByItemTypeButton: locate('span').withText('Filter by item type').inside(locate('button')),
    toggleTreeViewItemsButton: locate('div').withAttr({ class: 'dx-treeview-toggle-item-visibility' }),
    deleteReferenceDigitalAsset: '#ebsContainerContent_applicationDependency_applicationId_application_default_toolbar_item_2',
    deselectAllDigitalAssetsButton: locate('span').withText('Deselect all digital assets'),
    deselectAllItemTypesButton: locate('span').withText('Deselect all item types'),
    addNewStyleSheetButtonCodeEditor: locate('li').withAttr({ 'aria-label': 'Add new Style Sheet' }),
    searchMenuItemButton: locate('i').withAttr({ class: 'pe-7s-search dsg-home-search-icon' }).inside('#searchMenuHolder'),
    styleSheetButton: locate('span').withText('Style Sheets'),
  },
  containers: {
    tabContainer: '#stepper',
    defaultContainer: '#ebsContainerContent',
    migrationContainer: '#applicationMigration',
    minimumPlatformVersionContainer: '#ebsContainerContent_minPlatformVersion_popupLkp_lookupgrid',
    ciDataContainer: '#CIDataGridContainer',
    ciContainer: '#ftosApplicationCIListHolder',
    customizationSetTableContainer: '#ebsContainerContent_customizationSetId_popupLkp_lookupgrid',
    containerForReferencedDigitalAsset: '#ebsContainerContent_refApplicationId_popupLkp_lookupgrid',
    applicationDependencyContainer: '#ebsContainerContent_applicationDependency_applicationId_application_default',
    dataImportFilesContainer: '#ebsContainerContent_applicationDataImport_applicationId_application_forApplication',
    typeDataImportContainer: '#ebsContainerContent_type_list',
    dataImportTemplateContainer: '#ebsContainerContent_dataImportId_popupLkp_lookupgrid',
    dataConfigDefinitionContainer: '#ebsContainerContent_dataConfigDefinitionId_popupLkp_lookupgrid',
    searchDAContainer: locate('tr').withAttr({ 'aria-rowindex': '1' }).inside('#ebsContainerContent'),
    filterContainer: '#ebsContainer > div.main-container.with-sidebar > div > div.ftos-pnl-not-right.ftos-panel-item.ftos-panel-wrap > div.ftos-pnl-left.ftos-panel-item.ftos-panel-wrap > div.ftos-pnl-middle-left.ftos-panel-item > div > div > div > div > div > div.dx-scrollable-content > ul',
  },
  select: {
    businessEntity: locate('div').withText('Business Entity').inside('div').withAttr({ role: 'option' }),
    businessEntityExtension: locate('div').withText('Business Entity Extension').inside('div').withAttr({ role: 'option' }),
    businessEntityForm: locate('div').withText('EntityForm').inside('div').withAttr({ role: 'option' }),
    businessEntityView: locate('div').withText('EntityView').inside('div').withAttr({ role: 'option' }),
    businessWorkflow: locate('div').withText('Business Workflow').inside('div').withAttr({ role: 'option' }),
    businessWorkflowConfiguration: locate('div').withText('Business Workflow Configuration').inside('div').withAttr({ role: 'option' }),
  },
  tabs: {
    dependenciesTab: locate('span').withText('Dependencies'),
    configurationItemsTab: locate('span').withText('Configuration Items'),
    relatedProjectsTab: locate('span').withText('Related Digital Solutions'),
    dataImportFilesTab: locate('span').withText('Data Import Files'),
    configurationItemsMigrationTab: locate('span').withText('Configuration Items Migration'),
    generalTab: locate('span').withText('General'),
  },
  checkbox: {
    isMigratedCheckboxContainer: locate('td').withAttr({ 'aria-colindex': '5' }).inside(locate('tr').withAttr({ 'aria-rowindex': '1' })),
    obsoleteCheckbox: locate('div').withAttr({ id: 'ebsContainerContent_obsolete' }).withAttr({ 'aria-checked': 'true' }),
  },
  selector: {
    existingDigitalAssetMigrationContainer: locate('td').withAttr({ 'aria-colindex': '6' }).inside(locate('tr').withAttr({ 'aria-rowindex': '1' })),
    branchDigitalAssetDropdown: '#lookup-grouped',
    dropdownOption: locate('div').withAttr({ role: 'option' }),
    firstPositionTableRow: locate('td').withAttr({ 'aria-colindex': '1' }),
    pageTable: locate('div').withAttr({ class: 'dx-page' }),
    locatorForCIItem: locate('input').withAttr({ type: 'text' }).inside('#typeCtrl'),
    addDataImportTemplateFile: locate('input').withAttr({ type: 'file' }).inside('#ebsContainerContent_importFile_uploader'),
    entitiesCodeEditorOption: locate('li').withAttr({ 'aria-label': 'Entities' }),
    thirdLevelCodeEditorOption: locate('li').withAttr({ 'aria-level': '3' }),
    secondLevelCodeEditorOption: locate('li').withAttr({ 'aria-level': '2' }),
    codeEditorRightHandPanelHolder: locate('div').withAttr({ class: 'ftos-ce-props-holder' }),
    filterByOptionsCodeEditor: locate('div').withAttr({ class: 'dropdown-item checkbox checkbox-sm checkbox-color1' }),
    entityRecordByOptionsCodeEditor: locate('div').withAttr({ class: 'dx-treeview-toggle-item-visibility' }),
    filterByDAClass: locate('div').withAttr({ class: 'dropdown-item checkbox checkbox-sm checkbox-color1' }),
  },
  table: {
    tableConfigItemsDataTypeTable: '#CIDataGridContainer',
    configItemsDataContainerTable: '#ftosApplicationCIListHolder',
  },
  labels: {
    displayNameLabelCodeEditor: locate('h6').withText('Display Name'),
    displayNameCollectionLabelCodeEditor: locate('h6').withText('Display Collection Name'),
    showInMenuLabelCodeEditor: locate('h6').withText('Show In Menu'),
    primaryAttributeLabelCodeEditor: locate('h6').withText('Primary Attribute'),
    tableNameLabelCodeEditor: locate('h6').withText('Table Name'),
    defaultEntityStatusLabelCodeEditor: locate('h6').withText('Default Entity Status'),
    isAuditedLabelCodeEditor: locate('h6').withText('Is Audited'),
    dataOptimizationLabelCodeEditor: locate('h6').withText('Data Optimization'),
    isSystemEntityLabelCodeEditor: locate('h6').withText('Is System Entity'),
  },
};
