module.exports = {
  fields: {
    businessEntityResultsField: locate('tbody').withAttr({ role: 'presentation' }).inside(locate('div').withAttr({ id: 'ebsContainerContent' })),
    insertEntityLastField: locate('div').withAttr({ id: 'ebsContainerContent_BWId' }),
    entityTypeField: locate('input').withAttr({ class: 'dx-texteditor-input' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_entityType' })),
    entityTypeReadOnlyField: locate('input').withAttr({ 'aria-readonly': 'true' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_entityType' })),
    entityNameField: locate('input').withAttr({ class: 'dx-texteditor-input' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_name' })),
    entityNameReadOnlyField: locate('input').withAttr({ 'aria-readonly': 'true' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_name' })),
    entityDisplayNameField: locate('input').withAttr({ class: 'dx-texteditor-input' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_displayName' })),
    entityCollectionNameField: locate('input').withAttr({ class: 'dx-texteditor-input' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_displayCollectionName' })),
    entityDescriptionField: locate('textarea').withAttr({ class: 'dx-texteditor-input' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_description' })),
    entityPANameField: locate('input').withAttr({ class: 'dx-texteditor-input' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_primaryAttributeName' })),
    entityPANameReadOnlyField: locate('input').withAttr({ 'aria-readonly': 'true' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_primaryAttributeName' })),
    entityPADisplayNameField: locate('input').withAttr({ class: 'dx-texteditor-input' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_primaryAttributeDisplayName' })),
    entityPADisplayNameReadOnlyField: locate('input').withAttr({ 'aria-readonly': 'true' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_primaryAttributeDisplayName' })),
    entityStatusField: locate('input').withAttr({ class: 'dx-texteditor-input' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_defaultEntityStatusId' })),
    entityExtendedModelField: locate('div').withAttr({ id: 'ebsContainerContent_sys_entity_sys_attribute_entityView' }),
    entityExtendedFormsFields: locate('div').withAttr({ id: 'ebsContainerContent_sys_entity_sys_entityform_basicForms' }),
    entityExtendedViewsFields: locate('div').withAttr({ id: 'ebsContainerContent_sys_entity_sys_entityview' }),
    entityColumnField: locate('td').withAttr({ 'aria-label': 'Column Name' }),
    entitySearchField: locate('input').withAttr({ class: 'dx-texteditor-input' }).inside(locate('td').withAttr({ 'aria-label': 'Column DisplayName, Filter cell' })),
    entitySearchResultsField: locate('tr').withAttr({ role: 'row' }),
    entityListViewField: locate('div').withAttr({ id: 'listViewContainerId' }),
    attrReadOnlyField: locate('div').withAttr({ id: 'ebsContainerContent_isReadonly' }),
    attrNameField: locate('input').withAttr({ class: 'dx-texteditor-input' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_name' })),
    attrTypeField: locate('input').withAttr({ class: 'dx-texteditor-input' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_attributeTypeId_list' })),
    attrDisplayName: locate('input').withAttr({ class: 'dx-texteditor-input' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_displayName' })),
    attrTableColumnNameField: locate('input').withAttr({ class: 'dx-texteditor-input' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_tableColumnName' })),
    attrRONameField: locate('input').withAttr({ readonly: '' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_name' })),
    attrROTypeField: locate('input').withAttr({ readonly: '' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_attributeTypeId_list' })),
    attrROExternal: locate('div').withAttr({ id: 'ebsContainerContent_isExternalId' }).withAttr({ 'aria-disabled': 'true' }),
    attrROColumnNameField: locate('input').withAttr({ readonly: '' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_tableColumnName' })),
    attrROLookupField: locate('input').withAttr({ readonly: '' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_lookupToEntityName_textBox' })),
    attrROLookupRelField: locate('input').withAttr({ readonly: '' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_lookupRelationshipName' })),
    attrLookupSearchFiled: locate('input').withAttr({ class: 'dx-texteditor-input' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_lookupToEntityName_popupLkp_lookupgrid' })),
    attrLookupRelFiled: locate('input').withAttr({ class: 'dx-texteditor-input' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_lookupRelationshipName' })),
    lookupCorrelationField: locate('div').withAttr({ id: 'ebsContainerContent_lookupCorrelationAttribute_parentLookupId_attribute_wrap' }),
    attributeTooltipField: locate('textarea').withAttr({ class: 'dx-texteditor-input' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_tooltip' })),
    baseAttrLookupField: locate('input').withAttr({ class: 'dx-texteditor-input' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_baseAttributeId_dataGrid' })),
    refAttrLookupField: locate('input').withAttr({ class: 'dx-texteditor-input' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_referencedAttributeId_dataGrid' })),
    lookupAttrROField: locate('input').withAttr({ 'aria-readonly': 'true' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_LookupExternal_textBox' })),
  },
  buttons: {
    entityInsertButton: locate('a').withAttr({ id: 'InsertBtn' }),
    entityTypeButton: locate('input').withAttr({ class: 'dx-texteditor-input' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_entityType_list' })),
    entityStatusButton: locate('div').withAttr({ id: 'ebsContainerContent_defaultEntityStatusId_button' }),
    insertAttributeButton: locate('div').withAttr({ id: 'ebsContainerContent_sys_entity_sys_attribute_entityView_toolbar_item_1' }),
    deleteAttributeButton: locate('div').withAttr({ id: 'ebsContainerContent_sys_entity_sys_attribute_entityView_toolbar_item_2' }),
    attrLookupToEntityButton: locate('div').withAttr({ class: 'dx-button-content' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_lookupToEntityName_button' })),
    attrInsertCorrButton: locate('div').withAttr({ id: 'ebsContainerContent_lookupCorrelationAttribute_parentLookupId_attribute_toolbar_item_1' }),
    attrDeleteCorrButton: locate('div').withAttr({ id: 'ebsContainerContent_lookupCorrelationAttribute_parentLookupId_attribute_toolbar_item_2' }),
    baseAttrLookupButton: locate('div').withAttr({ class: 'dx-button-content' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_baseAttributeId_dropDownBox' })),
    reffAttrLookupButton: locate('div').withAttr({ class: 'dx-button-content' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_referencedAttributeId_dropDownBox' })),
  },
  popup: {
    entityStatusTable: locate('div').withAttr({ id: 'ebsContainerContent_defaultEntityStatusId_popupLkp_lookupgrid_wrap' }),
  },
  selector: {
    externalEntityTypeSelector: locate('p').withAttr({ title: 'External Source Data' }).inside(locate('div').withAttr({ class: 'dx-scrollview-content' })),
    isAuditedCheckbox: locate('div').withAttr({ id: 'ebsContainerContent_isAudited' }),
    isAuditedCheckboxTrue: locate('div').withAttr({ id: 'ebsContainerContent_isAudited', 'aria-checked': 'true' }),
    isAuditedCheckboxFalse: locate('div').withAttr({ id: 'ebsContainerContent_isAudited', 'aria-checked': 'false' }),
    optimizeSearchCheckbox: locate('div').withAttr({ id: 'ebsContainerContent_dataOptimization' }),
    optimizeSearchCheckboxTrue: locate('div').withAttr({ id: 'ebsContainerContent_dataOptimization', 'aria-checked': 'true' }),
    optimizeSearchCheckboxFalse: locate('div').withAttr({ id: 'ebsContainerContent_dataOptimization', 'aria-checked': 'false' }),
    attrIsExternalIdCheckbox: locate('div').withAttr({ id: 'ebsContainerContent_isExternalId' }),
    attrTypeSelector: locate('p').withAttr({ title: 'Uniqueidentifier' }).inside(locate('div').withAttr({ class: 'dx-scrollview-content' })),
    attrTypeLookupSelector: locate('p').withAttr({ title: 'Lookup' }).inside(locate('div').withAttr({ class: 'dx-scrollview-content' })),
    attrReadOnlyCheckedField: locate('div').withAttr({ id: 'ebsContainerContent_isReadonly' }).withAttr({ 'aria-checked': 'true' }),
    refAttrValueSelect: '//*[@id="ebsContainerContent_referencedAttributeId_dataGrid"]/div/div[6]/div/div/div[1]/div/table/tbody/tr[1]/td[1]',
  },
  container: {
    defaultContainer: '#ebsContainerContent',
    dataModelTableContainer: '#ebsContainerContent_sys_entity_sys_attribute_entityView',
  },
};
