module.exports = {
  fields: {
    inputCodeFieldOptionField: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_Code' })),
    inputNameFieldOptionField: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_Name' })),
    inputValueFieldOptionField: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_Value' })),
    inputFOVARCity_CodeField: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_AT_FOVARCityId_Code' })),
    inputFOVARCountry_CodeField: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_AT_FOVARCityId_AT_FOVARCountryId' })),
    inputFOVARCountry_RelatedCodeField: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'Column Name, Filter cell' })).inside('#ebsContainerContent_AT_FOVARCityId_AT_FOVARCountryId_dataGrid'),
    viewLookupSearchField: locate('input').withAttr({ type: 'text' }).inside(locate('td').withAttr({ 'aria-label': 'Column View Name, Filter cell' })).inside('#ebsContainerContent_lookupViewId_popupLkp_lookupgrid'),
    inputCodeReadOnlyField: locate('input').withAttr({ 'aria-readonly': 'true' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_Code' })),
    noDataField: locate('.dx-datagrid-nodata').inside('#ebsContainerContent_sys_entityformoptionfield_entityform'),
    inputEntityType: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_entityType_list' })),
    inputCountryNameField: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_AT_ForFieldOptCountryId_textBox' })),
    attributeField: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_attributeId_textBox' })),
  },
  container: {
    lookupAsDropdownContainer: '#ebsContainerContent_Lookup_dataGrid',
    lookupAsDDCityContainer: '#ebsContainerContent_AT_FOVARCityId_popupLkp_lookupgrid',
    lookupAsDDCountryRelatedCodeContainer: '#ebsContainerContent_AT_FOVARCityId_AT_FOVARCountryId_dataGrid',
    lookupAsDDCountryContainer: '#ebsContainerContent_AT_ForFieldOptCountryId_popupLkp_lookupgrid',
    defaultContainerContent: locate('div').withAttr({ id: 'ebsContainerContent' }),
    anchorContainerForFieldOption: '#ebsContainerContent_attributeId_popupLkp_lookupgrid'
  },
  buttons: {
    lookupAsDropdownButton: locate('div').withAttr({ role: 'button' }).inside('#ebsContainerContent_Lookup_dropDownBox'),
    lookupAsDropdownCityButton: locate('div').withAttr({ role: 'button' }).inside('#ebsContainerContent_AT_FOVARCityId'),
    okLookupTableButton: '#ebsContainerContent_AT_FOVARCityId_popupLkp_lookupgrid_toolbar_item_4',
    lookupAsDropdownCountryButton: locate('div').withAttr({ role: 'button' }).inside('#ebsContainerContent_AT_FOVARCityId_AT_FOVARCountryId_dropDownBox'),
    lookupCountryButton: locate('div').withAttr({ id: 'ebsContainerContent_AT_FOVARCityId_AT_FOVARCountryId_dropDownBox' }),
    lookupCountryFOButton: locate('div').withAttr({ id: 'ebsContainerContent_AT_ForFieldOptCountryId_button' }),
    secondStep: locate('p').withText('2').inside('#ew-controllers'),
    lookupAsDropdownViewButton: '#ebsContainerContent_lookupViewId_button',
    okAttribute: '#ebsContainerContent_lookupViewId_popupLkp_lookupgrid_toolbar_item_3',
    dropdownViewCityButton: locate('div').withAttr({ role: 'button' }).inside('#ebsContainerContent_AT_ForFieldOptCityId_dropDownBox'),
    editCityButton: locate('div').withAttr({ id: 'ebsContainerContent_AT_ForFieldOptCityId_editButton' }),
    editCountryButton: locate('div').withAttr({ id: 'ebsContainerContent_AT_ForFieldOptCountryId_buttonEdit' }),
    insertPopupButton: locate('div').withText('Insert').inside('#ebsContainerContent_AT_ForFieldOptCountryId_popupLkp_lookupgrid_toolbar'),
    iconForSearchForText: locate('div').withAttr({ role: 'menuitem' }).inside(locate('td').withAttr({ 'aria-colindex': '1' })).inside('#ebsContainerContent_attributeId_popupLkp_lookupgrid'),
    iconForSearchForEquals: locate('i').withAttr({ class: 'dx-icon dx-icon-filter-operation-equals' }),
  },
  checkbox: {
    makeReadOnly: '#ebsContainerContent_fieldIsReadOnly',
    radioButtonYes: locate('div').withAttr({ role: 'radio' }).withDescendant(locate('div').withText('Yes')).inside(locate('div').withAttr({ id: 'ebsContainerContent_Bool' })),
    showEditButtonCheckbox: locate('span').inside('#ebsContainerContent_lookupShowEditButton'),
    useVirtualAttributeCheckbox: locate('.dx-checkbox-container').inside('#ebsContainerContent_useVirtualAttribute'),
    showInsertButtonDefaultCheckbox: locate('div').withAttr({ 'aria-checked': 'mixed' }).withAttr({ id: 'ebsContainerContent_lookupShowInsertButton' }),
    showInsertButtonCheckedCheckbox: locate('div').withAttr({ 'aria-checked': 'true' }).withAttr({ id: 'ebsContainerContent_lookupShowInsertButton' }),
    showInsertButtonUnCheckCheckbox: locate('div').withAttr({ 'aria-checked': 'false' }).withAttr({ id: 'ebsContainerContent_lookupShowInsertButton' }),
    showEditButtonDefaultCheckbox: locate('div').withAttr({ 'aria-checked': 'mixed' }).withAttr({ id: 'ebsContainerContent_lookupShowEditButton' }),
    showEditButtonCheckedCheckbox: locate('div').withAttr({ 'aria-checked': 'true' }).withAttr({ id: 'ebsContainerContent_lookupShowEditButton' }),
    showEditButtonUnCheckCheckbox: locate('div').withAttr({ 'aria-checked': 'false' }).withAttr({ id: 'ebsContainerContent_lookupShowEditButton' }),
  },
  tabs: {
    fieldOptionsTab: locate('div').withChild(locate('span').withText('Field Options')),
  },
  table: {
    secondRowEntityFormTable: locate('tr').withAttr({ 'aria-rowindex': '2' }).inside('#ebsContainerContent_sys_entityformoptionfield_entityform'),
    fourthElementRowOfTableIsCheck: locate('div').withAttr({ 'aria-checked': 'true' }).inside(locate('td').withAttr({ 'aria-colindex': '4' })).inside(locate('tr')),
    thirdElementRowOfTableIsEmpty: locate('td').withText('').withAttr({ 'aria-colindex': '3' }).inside(locate('tr')),
  },
};
