module.exports = {
  fields: {
    ffInputAttrToFilter: locate('input').withAttr({ role: 'textbox' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_attributeToFilter' })),
    ffInputAttrToFilterRef: locate('input').withAttr({ role: 'textbox' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_attributeToFilterReference' })),
    ffInputAttrToFilterBy: locate('input').withAttr({ role: 'textbox' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_attributeToFilterBy' })),
    ffInputPortalEntityName: locate('input').withAttr({ role: 'textbox' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_Name' })),
    ffInputPortalEntityCityDropdown: locate('input').withAttr({ role: 'combobox' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_AT_ForFFCityId' })),
    ffInputPortalEntityCountryDropdown: locate('input').withAttr({ role: 'combobox' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_AT_ForFFCountryId' })),
    ffInputPortalEntityCityPopup: locate('input').withAttr({ role: 'textbox' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_AT_ForFFCityId' })),
    ffInputPortalEntityCountryPopup: locate('input').withAttr({ role: 'textbox' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_AT_ForFFCountryId' })),
    ffCityLookupSearchFieldPopup: locate('input').withAttr({ role: 'textbox' }).inside(locate('td').withAttr({ role: 'gridcell' }).withAttr({ 'aria-colindex': '1' })).inside(locate('div').withAttr({ id: 'ebsContainerContent_AT_ForFFCityId_popupLkp_lookupgrid' })),
    ffCityLookupSearchFieldDropdown: locate('input').withAttr({ role: 'textbox' }).inside(locate('td').withAttr({ role: 'gridcell' }).withAttr({ 'aria-colindex': '1' })).inside(locate('div').withAttr({ id: 'ebsContainerContent_AT_ForFFCityId_dataGrid' })),
  },
  buttons: {
    cancelPopupButton: locate('div').withAttr({ id: 'ebsContainerContent_AT_ForFFCountryId_popupLkp_lookupgrid_toolbar_item_1' }),
    okPopupCountryButton: '#ebsContainerContent_AT_ForFFCountryId_popupLkp_lookupgrid_toolbar_item_4',
    okPopupCityButton: '#ebsContainerContent_AT_ForFFCityId_popupLkp_lookupgrid_toolbar_item_4',
  },
  selector: {
    ffDataFormsTable: locate('div').withAttr({ class: 'dx-datagrid-content' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_sys_entity_sys_entityform_basicForms' })),
    ffUserJourneysTable: locate('div').withAttr({ id: 'ftosFormJourneysHolder' }),
    ffInputPortalEntityCountryDropdownBtn: locate('div').withAttr({ role: 'button' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_AT_ForFFCountryId_dropDownBox' })),
    ffInputPortalEntityCityDropdownBtn: locate('div').withAttr({ role: 'button' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_AT_ForFFCityId_dropDownBox' })),
    ffFilterFieldsTable: locate('div').withAttr({ id: 'ebsContainerContent_entityformfilteredfield_entityform' }),
    ffInputPortalEntityCountryPopupBtn: locate('div').withAttr({ role: 'button' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_AT_ForFFCountryId' })),
    ffInputPortalEntityCityPopupBtn: locate('div').withAttr({ role: 'button' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_AT_ForFFCityId' })),
    ffCityLookupTablePopup: locate('div').withAttr({ id: 'ebsContainerContent_AT_ForFFCityId_popupLkp_lookupgrid' }),
    ffCountryLookupTablePopup: locate('div').withAttr({ id: 'ebsContainerContent_AT_ForFFCountryId_popupLkp_lookupgrid' }),
    ffCityLookupTableDropdown: locate('div').withAttr({ id: 'ebsContainerContent_AT_ForFFCityId_dataGrid' }),
    ffCountryLookupTableDropdown: locate('div').withAttr({ id: 'ebsContainerContent_AT_ForFFCountryId_dataGrid' }),
    ffInputSectionCountryPopupBtn: locate('div').withAttr({ id: 'ebsContainerContent_AT_ForFFCountryId_button' }),
    ffSectionCountryLookupTable: locate('div').withAttr({ id: 'ebsContainerContent_AT_ForFFCountry_popupLkp_lookupgrid' }),
  },
};
