module.exports = {
  fields: {
    flowControlRuleNameField: locate('input').withAttr({ role: 'textbox' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_name' })),
    flowControlNamePortalField: locate('input').withAttr({ role: 'textbox' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_Name' })),
    conditionValueTextField: '//*[@id="ebsContainerContent_condition_filter_filterBuilder"]/div/div[2]/div/div/div[4]/div/div/div[1]/input',
    enterValueField: '#ebsContainerContent_condition_filter_filterBuilder > div > div.dx-filterbuilder-group-content > div > div > div.dx-filterbuilder-text.dx-filterbuilder-item-value > div',
    searchNameField: locate('input').withAttr({ type: 'text' }).inside(locate('td').withAttr({ 'aria-label': 'Column Name, Filter cell' })),
    nameInputField: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_name'),
    descriptionInputField: locate('textarea').withAttr({ role: 'textbox' }).inside('#ebsContainerContent_description'),
    defineRuleExpressionItemField: locate('div').withAttr({ class: 'dx-filterbuilder-text dx-filterbuilder-item-field' }),
    enterAValueInputField: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ class: 'dx-filterbuilder-text dx-filterbuilder-item-value' })),
    closeFlowHomepageInputField: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_AT_FlowControl_CloseFlowHomepageRule_E01'),
    closeFlowPreviousContextInputField: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_AT_FlowControl_CFPCR_E01'),
    closeFlowListInputField: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_AT_FlowControl_CloseFlowListRule_E01'),
    entityViewField: '#ebsContainerContent_closeFlowEntityViewId_dropDownBox',
    entityViewSearchField: locate('input').withAttr({ type: 'text' }).inside(locate('td').withAttr({ 'aria-label': 'Column Entity, Filter cell' })),
    closeFlowDashboardInputField: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_AT_FlowControl_CloseFlowDashboardRule_01'),
    cancelNavigationInputField: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_cancelNavigationMsg'),
    lookupInputAT_Flow_control_E01Field: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_AT_Flow_control_E01_Lookup_textBox'),
    lookupInputAT_Flow_control_E02Field: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_AT_Flow_control_E02_Lookup_textBox'),
    defineRuleExpressionOperationField: locate('div').withAttr({ class: 'dx-filterbuilder-text dx-filterbuilder-item-operation' }),
    cancelNavigationPortalInputField: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_AT_FlowControl_CloseFlowNavigation_01'),
    selectDigitalJourneyFlowInputField: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_nextFormId_dropDownBox'),
    primaryKeyAttributeInputField: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_primaryKeyValueAttributeId_dropDownBox'),
    textAT_FlowControl_RuleNok_E01InputField: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_AT_Flow_control_ruleNok_E01'),
    textAT_FlowControl_RuleNok_E02InputField: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_AT_Flow_control_ruleNok_E02'),
    textAT_FlowControl_E01InputField: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_AT_Flow_control_E01'),
    textAT_FlowControl_E02InputField: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_AT_Flow_control_E02'),
    inputActionNamePopupField: locate('input').withAttr({ type: 'text' }).inside('.ebs-grid-action-popup-action-name'),
    itemValueTextField: locate('.dx-filterbuilder-item-value-text'),
    statusNewToInProgressField: locate('div').withText('New -> InProgress'),
    statusInProgressToApprovedField: locate('div').withText('InProgress -> Approved'),
    statusNewToApprovedField: locate('div').withText('New -> Approved'),
    statusToStatusField: locate('.dx-filterbuilder-item-value-text'),
    actionsToBePerformedField: locate('div').withText('No data to display'),
    invarDate1InputField: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_invar_date1'),
    invarDate2InputField: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_invar_date2'),
    textAT_FlowControl_text_att_E01: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_AT_FlowControl_text_att_E01'),
    textAT_FlowControl_text_att_E02: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_AT_FlowControl_text_att_E02'),
    inputNameField: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_Name' })),
    lookupE01_InputField: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_Lookup_E01ToE02_textBox' })),
    closeFlowEntityField: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_closeFlowEntityId_textBox'),
    isBetweenDateFirstField: '#date2',
    isBetweenDateSecondField: locate('input').withAttr({ id: 'date2' }).last(),
    portalEntityTextField: locate('input').withAttr({ type: 'text' }),
    portalEntityTextArea: locate('textarea').inside(locate('div')),
  },
  buttons: {
    insertNewRuleBtn: '#ebsContainerContent_entityFormSectionRule_formSection_entityformsection_toolbar_item_1',
    deleteRuleBtn: '#ebsContainerContent_entityFormSectionRule_formSection_entityformsection_toolbar_item_2',
    plusAddNewRuleBtn: '#ebsContainerContent_condition_filter_filterBuilder div div div.dx-filterbuilder-action',
    parentConditionTypeButton: '//html[@id=\'main-page\']//div[@id=\'ebsContainerContent_condition_filter_filterBuilder\']/div[@class=\'dx-filterbuilder-group\']//div[.=\'Checking with Custom Processor\']',
    childSecondConditionOperatorButton: '#ebsContainerContent_condition_filter_filterBuilder > div > div.dx-filterbuilder-group-content > div > div > div.dx-filterbuilder-text.dx-filterbuilder-item-operation',
    goToSectionButton: locate('div').withAttr({ role: 'button' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_goToSection' })),
    previousButton: locate('button').withText('Previous'),
    businessConditionButton: '#ebsContainerContent_condition_filter_filterBuilder > div > div.dx-filterbuilder-group-content > div > div > div.dx-filterbuilder-text.dx-filterbuilder-item-value > div > div > div > div > div.dx-texteditor-buttons-container > div.dx-button-normal.dx-button-mode-contained.dx-widget.dx-dropdowneditor-button',
    okPopupButton: '#ebsContainerContent_LookUpAtt_popupLkp_lookupgrid_toolbar_item_4',
    addLookupAttributeButton: '#ebsContainerContent_LookUpAtt_button',
    addNewRuleConditionBtn: locate('.dx-item').inside(locate('li').withAttr({ 'aria-label': 'Add Condition' })),
    ruleAddNamePkidBtn: locate('.dx-item').inside(locate('li').withAttr({ 'data-item-id': 'AT_EntFControlBCIsFulfilledPkid' })),
    ruleAddNameLkidBtn: locate('.dx-item').inside(locate('li').withAttr({ 'data-item-id': 'LookUpAtt' })),
    ruleBCIsFulfilledBtn: locate('.dx-item').inside(locate('li').withAttr({ 'aria-label': 'Business Condition is fulfilled' })),
    ruleBCIsNotFulfilledBtn: locate('.dx-item').inside(locate('li').withAttr({ 'aria-label': 'Business Condition is Not fulfilled' })),
    uiDesignerButton: '#mceu_19-button',
    applyChangesAttributeButton: locate('button').withText('Apply changes').inside(locate('div').withAttr({ class: 'ftos-panel-item' })).at(2),
    updateTemplateButton: locate('button').withText('Update template').inside(locate('div').withAttr({ role: 'toolbar' })),
    uiDesigner62Button: '#mceu_62-button',
    addDefineRuleExpressionButton: locate('div').withAttr({ class: 'dx-filterbuilder-action-icon dx-icon-plus dx-filterbuilder-action' }).inside('#ebsContainerContent_condition_filter_filterBuilder'),
    enterAValueButton: locate('div').withAttr({ class: 'dx-filterbuilder-item-value-text' }).withText('<enter a value>').inside(locate('div').withAttr({ class: 'dx-filterbuilder-group-content' })),
    addConditionDefineRuleButton: locate('li').withAttr({ 'aria-label': 'Add Condition' }),
    nextButton: locate('button').withText('Next'),
    addDashboardCloseFlowButton: '#ebsContainerContent_closeFlowDashboardId_button',
    okButtonDashboardCloseFlow: '#ebsContainerContent_closeFlowDashboardId_popupLkp_lookupgrid_toolbar_item_4',
    finishButton: locate('button').withText('Finish'),
    arrowDownButtonAT_FlowControl_E02: '#ebsContainerContent_AT_Flow_control_E02_Lookup_button',
    okButtonAT_FlowControl_E02: '#ebsContainerContent_AT_Flow_control_E02_Lookup_popupLkp_lookupgrid_toolbar_item_4',
    lookupArrowDownAT_Flow_control_ruleNok_E01Button: '#ebsContainerContent_AT_Flow_control_ruleNok_E01_Lookup_button',
    okButtonLookupAT_Flow_control_ruleNok_E01: '#ebsContainerContent_AT_Flow_control_ruleNok_E01_Lookup_popupLkp_lookupgrid_toolbar_item_4',
    lookupArrowDownAT_Flow_control_ruleNok_E02Button: '#ebsContainerContent_AT_Flow_control_ruleNok_E02_Lookup_button',
    okButtonLookupAT_Flow_control_ruleNok_E02: '#ebsContainerContent_AT_Flow_control_ruleNok_E02_Lookup_popupLkp_lookupgrid_toolbar_item_4',
    lookupArrowDownAT_Flow_control_E01: '#ebsContainerContent_AT_Flow_control_E01_Lookup_button',
    okButtonLookupAT_Flow_control_E01: '#ebsContainerContent_AT_Flow_control_E01_Lookup_popupLkp_lookupgrid_toolbar_item_4',
    lookupArrowDownAT_Flow_control_E02: '#ebsContainerContent_AT_Flow_control_E02_Lookup_button',
    okButtonLookupAT_Flow_control_E02: '#ebsContainerContent_AT_Flow_control_E02_Lookup_popupLkp_lookupgrid_toolbar_item_4',
    insertFormActionsBtn: locate('.dx-icon-add').inside('#ebsContainerContent_formActions'),
    filterExecuteBtn: locate('div').withText('execute'),
    iconPlusPopupBtn: locate('.dx-icon-plus'),
    savePopupActionBtn: locate('.ebs-grid-action-popup-save'),
    businessTransactionButton: '#HistoryBtn',
    editActionBtn: locate('.dx-icon-edit').inside('#ebsContainerContent_formActions'),
    removeActionBtn: locate('.dx-icon-close').inside('#ebsContainerContent_formActions'),
    actionBtn: '#actionsButton',
    applyActionBtn: locate('button').withText('Apply'),
    recordFinishButton: locate('button').withText('Finish').inside('#ebsContainerContent'),
    dropdownLookup_E01ToE02Button: locate('div').withAttr({ id:'ebsContainerContent_Lookup_E01ToE02_button'}),
    dropdownLookup_E02ToE03Button: locate('div').withAttr({ id:'ebsContainerContent_Lookup_E02ToE03_button'}),
    dropdownLookup_E03ToE01Button: locate('div').withAttr({ id:'ebsContainerContent_Lookup_E03ToE01_button'}),
    dropdownLookup_E02ToE01Button: locate('div').withAttr({ id:'ebsContainerContent_Lookup_E02ToE01_button'}),
    okPopupLookup_E01ToE02Button: locate('div').withAttr({ id:'ebsContainerContent_Lookup_E01ToE02_popupLkp_lookupgrid_toolbar_item_4'}),
    okPopupLookup_E02ToE03Button: locate('div').withAttr({ id:'ebsContainerContent_Lookup_E02ToE03_popupLkp_lookupgrid_toolbar_item_4'}),
    okPopupLookup_E03ToE01Button: locate('div').withAttr({ id:'ebsContainerContent_Lookup_E03ToE01_popupLkp_lookupgrid_toolbar_item_4'}),
    okPopupLookup_E02ToE01Button: locate('div').withAttr({ id:'ebsContainerContent_Lookup_E02ToE01_popupLkp_lookupgrid_toolbar_item_4'}),
    okPopupLookupDashboardButton: locate('div').withAttr({ id:'ebsContainerContent_closeFlowDashboardId_popupLkp_lookupgrid_toolbar_item_4' }),
    navigateToDropdownListButton: locate('div').withAttr({ role:'button' }).inside('#ebsContainerContent_navigateTo_list'),
    dropdownCloseFlowEntityViewButton: locate('div').withAttr({ role:'button' }).inside('#ebsContainerContent_closeFlowEntityViewId_dropDownBox'),
    dropdownDashboardButton: locate('div').withAttr({ id:'ebsContainerContent_closeFlowDashboardId_button' }),
    defaultNextStepButton: locate('div').withAttr({ role:'button' }).inside('#ebsContainerContent_defaultNextStepId_dropDownBox'),
    digitalJourneyFlowDropdownButton: locate('div').withAttr({ role:'button' }).inside('#ebsContainerContent_nextFormId_dropDownBox'),
    nextSectionDropdownButton: locate('div').withAttr({ role:'button' }).inside('#ebsContainerContent_nextSectionId_dropDownBox'),
    attributeDropdownButton: locate('div').withAttr({ role:'button' }).inside('#ebsContainerContent_primaryKeyValueAttributeId_dropDownBox'),
    lookupArrowDownAT_FlowControl_lookup_att_E01Button: '#ebsContainerContent_AT_FlowControl_lookup_att_E01_Lookup_button',
    okButtonLookupAT_FlowControl_lookup_att_E01: '#ebsContainerContent_AT_FlowControl_lookup_att_E01_Lookup_popupLkp_lookupgrid_toolbar_item_4',
    lookupArrowDownAT_FlowControl_lookup_att_E03Button: '#ebsContainerContent_AT_FlowControl_lookup_att_E03_Lookup_button',
    okButtonLookupAT_FlowControl_lookup_att_E03: '#ebsContainerContent_AT_FlowControl_lookup_att_E03_Lookup_popupLkp_lookupgrid_toolbar_item_4',
    lookupArrowDownAT_FlowControl_lookup_att_E05Button: '#ebsContainerContent_AT_FlowControl_lookup_att_E05_Lookup_button',
    okButtonLookupAT_FlowControl_lookup_att_E05: '#ebsContainerContent_AT_FlowControl_lookup_att_E05_Lookup_popupLkp_lookupgrid_toolbar_item_4',
    removeButtonLookupAT_FlowControl_lookup_att_E05: '#ebsContainerContent_AT_FlowControl_lookup_att_E05_Lookup_popupLkp_lookupgrid_toolbar_item_2',
  },
  table: {
    flowControlSectionTable: '#ebsContainerContent_entityFormSectionRule_formSection_entityformsection',
    goToSectionStepTable: '#ebsContainerContent_goToSection_dataGrid',
    lookupPopupGridTable: '#ebsContainerContent_LookUpAtt_popupLkp_lookupgrid',
    firstRowTable: locate('tr').withAttr({ 'aria-rowindex': '1' }),
    secondRowTable: locate('tr').withAttr({ 'aria-rowindex': '2' }),
    actionIDTable: '#ebsContainerContent_formActions',
    rowMainDashboardTable: locate('td').withText('Main Dashboard').inside('#ebsContainerContent_closeFlowDashboardId_popupLkp_lookupgrid'),
    rowStep3Table: locate('td').withText('Step3').inside('#ebsContainerContent_defaultNextStepId_dataGrid'),
    rowStep2Table: locate('td').withText('Step2').inside('#ebsContainerContent_defaultNextStepId_dataGrid'),
    rowStep1SectionTable: locate('td').withText('Step1').inside('#ebsContainerContent_nextSectionId_dataGrid'),
  },
  labels: {
    modelTypeLabel: locate('h5').withAttr({ id: 'modelType' }),
    currentStatusNewLabel: locate('span').withText('New').inside(locate('.current-status')),
    currentStatusApprovedLabel: locate('span').withText('Approved').inside(locate('.current-status')),
    currentStatusInProgressLabel: locate('span').withText('InProgress').inside(locate('.current-status')),
    nextStatusClosedLabel: locate('a').withText('Closed').inside(locate('.next-status')),
    nextStatusApprovedLabel: locate('a').withText('Approved').inside(locate('.next-status')),
    reportLink: locate('a').withAttr({ id: 'ReportGroup0Btn' }),
    portalStep2Label: locate('span').withAttr({ class: 'journey-section-name' }).withText('Step2'),
    portalStep3Label: locate('span').withAttr({ class: 'journey-section-name' }).withText('Step3'),
    entityViewFlowControlLabel: locate('div').withText('Entity View'),
    entityViewListLabel: locate('h5').withText('AT_FC_CloseFlowList_E02 list'),
    mainDashboardLabel: locate('a').withText('Main Dashboard').inside('#ebsContainerContent'),
    mainDashboardLink: locate('a').withText('Main Dashboard').withAttr({ 'aria-selected': 'true' }).inside('#ebsContainerContent'),
    entityViewPrevContextLabel: locate('h5').withText('AT_FC_CloseFlowPrevContext_E01 list'),
  },
  list: {
    listOfActions: locate('.dx-filterbuilder-item-field'),
    changeBusinessList: locate('span').withText('Change Business Status from Status'),
    generateDigitalDocumentList: locate('span').withText('Generate Digital Document'),
    callCustomProcessorList: locate('span').withText('Call Custom Processor'),
    callBusinessMatrixList: locate('span').withText('Call Business Matrix'),
    callFormulaList: locate('span').withText('Call Formula with Data Mapping'),
    navigateToListOptionList: locate('p').withText('List').inside(locate('div').withAttr({ role: 'option' })),
    navigateToDashboardOptionList: locate('p').withText('Dashboard').inside(locate('div').withAttr({ role: 'option' })),
    navigateToHomepageOptionList: locate('p').withText('Homepage').inside(locate('div').withAttr({ role: 'option' })),
    navigateToPreviousContextOptionList: locate('p').withText('Previous Context').inside(locate('div').withAttr({ role: 'option' })),
  },
  selector: {
    selectBusinessCondition: '.dx-list-item-content',
    selectFirstBusinessCondition: locate('div').withAttr({ class: 'dx-item-content dx-list-item-content' }).first(),
    selectSecondBusinessCondition: locate('div').withAttr({ class: 'dx-item-content dx-list-item-content' }).last(),
    tabList: locate('div').withAttr({ id: 'stepper' }),
    attributeDataTemplateHTML: locate('div').withAttr({ 'data-component-type': 'attribute' }).inside(locate('div').withAttr({ class: 'container ftos-uid-html-holder' })),
    selectAttributeDropdown: locate('div').withAttr({ class: 'dx-selectbox dx-textbox dx-texteditor dx-dropdowneditor-button-visible dx-editor-outlined dx-texteditor-empty dx-widget dx-dropdowneditor dx-dropdowneditor-field-clickable' }),
    selectAttributeEmptyDropdown: locate('div').withAttr({ class: 'dx-selectbox dx-textbox dx-texteditor dx-dropdowneditor-button-visible dx-editor-outlined dx-widget dx-dropdowneditor dx-dropdowneditor-field-clickable dx-texteditor-empty' }),
    optionDropdown: locate('div').withAttr({ role: 'option' }),
    navigateToDropdown: '#ebsContainerContent_navigateTo_list',
    appsDashboard: locate('span').withText('Apps').inside(locate('ul').withAttr({ role: 'tablist' })),
    dashboardList: locate('ul').withAttr({ role: 'tablist' }),
    firstDDStatusList: locate('input').withAttr({ type: 'text' }).inside(locate('.dx-filterbuilder-item-value')),
    secondDDStatusList: locate('input').withAttr({ type: 'text' }).inside(locate('.dx-filterbuilder-item-value')).last(),
    customProcessorDDList: locate('div').withText('Custom Processor').withDescendant(locate('div').withAttr({ role: 'button' })).last(),
    actionsToBePerformedDD: '#ebsContainerContent_afterActions_container_multiselect',
    selectStepDropdown: '#ebsContainerContent_goToSection_dropDownBox',
    operationDefineRuleExpressionDropdown: locate('div').withAttr({ class: 'dx-filterbuilder-text dx-filterbuilder-item-operation' }),
    opSet1Dropdown: '#ebsContainerContent_opSet1_list',
    opSet2Dropdown: '#ebsContainerContent_opSet2_list',
    opSet3Dropdown: '#ebsContainerContent_opSet3_list',
  },
  checkbox: {
    selectAllActionsCheckbox: locate('.dx-list-select-all'),
    optionCloseFlowCheckbox: locate('div').withAttr({ id: 'ebsContainerContent_closeFlow' }),
    navigateToAnotherStepCheckedCheckbox: locate('div').withAttr({ role: 'radio' }).withAttr({ 'aria-selected': 'true' }).withDescendant(locate('div').withText('Navigate to another Step')),
    navigateToAnotherFlowCheckbox: locate('div').withAttr({ role: 'radio' }).withDescendant(locate('div').withText('Navigate to another Flow')),
    boolAttributeCheckbox: locate('div').withAttr({ id: 'ebsContainerContent_Bool_Attribute' }),
    isDefaultCheckbox: '#ebsContainerContent_isdefault',
    isDefaultForEditCheckbox: '#ebsContainerContent_isdefaultEdit',
    closeFlowCheckbox: '#ebsContainerContent_closeFlow',
    cancelNavigationCheckbox: '#ebsContainerContent_cancelNavigation',
    bool1CheckBox: '#ebsContainerContent_bool1',
    bool2CheckBox: '#ebsContainerContent_bool2',
  },
  toast: {
    stopCancelNavigationToast: locate('div').withText('STOP').withAttr({ class: 'jq-toast-single jq-has-icon jq-icon-warning' }),
  },
  containers: {
    defaultContainer: '#ebsContainerContent',
    stepsContainer: '#ebsContainerContent_sys_entityformsection_entityform_wrap',
    scrollableContainer: locate('div').withAttr({ class: 'dx-scrollable-content' }),
    entityViewContainer: '#ebsContainerContent_closeFlowEntityViewId_dataGrid',
    dashboardCloseFlowContainer: '#ebsContainerContent_closeFlowDashboardId_popupLkp_lookupgrid',
    goToAnotherFormContainer: '#ebsContainerContent_goToAnotherForm',
    primaryKeyAttributeContainer: '#ebsContainerContent_primaryKeyValueAttributeId_dataGrid',
    selectStepDropdown: '#ebsContainerContent_goToSection_dropDownBox',
  },
  status: {
    firstDDStatusList: locate('div').withAttr({ role: 'option' }),
    secondDDStatusList: locate('div').withAttr({ role: 'option' }),
    newStatusFirstDDList: locate('div').withText('New').inside(locate('div').withAttr({ role: 'option' })),
    inProgressStatusLastList: locate('div').withText('InProgress').inside(locate('div').withAttr({ role: 'option' })).last(),
    inProgressStatusList: locate('div').withText('InProgress').inside(locate('div').withAttr({ role: 'option' })),
    approvedStatusLastList: locate('div').withText('Approved').inside(locate('div').withAttr({ role: 'option' })).last(),
    actionReportDDList: locate('div').withText('AT_ActionReport01').inside(locate('div').withAttr({ role: 'option' })),
    actionScriptEndpointDDList: locate('div').withText('AT_ActionScriptEndpoint01').inside(locate('div').withAttr({ role: 'option' })).last(),
  },
  container: {
    lookup_E01ToE02Container: locate('div').withAttr({ id: 'ebsContainerContent_Lookup_E01ToE02_popupLkp_lookupgrid' }),
    lookup_E02ToE03Container: locate('div').withAttr({ id: 'ebsContainerContent_Lookup_E02ToE03_popupLkp_lookupgrid' }),
    lookup_E03ToE01Container: locate('div').withAttr({ id: 'ebsContainerContent_Lookup_E03ToE01_popupLkp_lookupgrid' }),
    lookup_E02ToE01Container: locate('div').withAttr({ id: 'ebsContainerContent_Lookup_E02ToE01_popupLkp_lookupgrid' }),
    lookupCloseFlowEntityViewContainer: locate('div').withAttr({ id: 'ebsContainerContent_closeFlowEntityViewId_dataGrid' }),
    digitalJourneyContainer: '#ebsContainerContent_nextFormId_dataGrid',
    primaryKeyAttributeContainer: locate('div').withAttr({ id: 'ebsContainerContent_primaryKeyValueAttributeId_dataGrid' }),
  },
};
