module.exports = {
  fields: {
    reportNameField: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_name' })),
    reportDisplayNameField: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_displayName' })),
    destinationField: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_destinationField' })),
    destinationFileNameField: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_destinationFileName' })),
    noDataReportItemField: locate('span').withText('No data').inside(locate('div').withAttr({ id: 'ebsContainerContent_sys_reportitem_report' })),
    reportStartDateField: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_startDate' })),
    reportEndDateField: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_endDate' })),
    inputReportPathField: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_reportPath' })),
    inputNameEditPageField: locate('input').inside('#ebsContainerContent_Name'),
    inputSearchReports: locate('input').withAttr({ type: 'text' }).inside(locate('td').withAttr({ 'aria-colindex': '2' })),
    errorReporting: locate('div').withText('Reporting Services Error. Check Log.'),
  },
  container: {
    containerContent: locate('div').withAttr({ id: 'ebsContainerContent' }),
    entityDDContainer: '#ebsContainerContent_entityId_popupLkp_lookupgrid',
    entityDataSourceDDContainer: '#ebsContainerContent_dataSource_popupLkp_lookupgrid',
    documentReportLkpContainer: '#ebsContainerContent_documentReportId_popupLkp_lookupgrid',
    reportItemWrapContainer: locate('div').withAttr({ id: 'ebsContainerContent_sys_reportitem_report_wrap' }),
  },
  buttons: {
    selectScopeBtn: locate('div').withAttr({ role: 'button' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_scope_list' })),
    selectTypeBtn: locate('div').withAttr({ role: 'button' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_type_list' })),
    selectReportTypeBtn: locate('div').withAttr({ role: 'button' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_reportRenderFormatId_list' })),
    searchForEntityDDBtn: '#ebsContainerContent_entityId_button',
    okPopupEntityLkpBtn: '#ebsContainerContent_entityId_popupLkp_lookupgrid_toolbar_item_4',
    selectOutputMethodBtn: locate('div').withAttr({ role: 'button' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_outputMethod_list' })),
    insertNewReportItemBtn: '#ebsContainerContent_sys_reportitem_report_toolbar_item_1',
    reportDocumentLkpBtn: '#ebsContainerContent_documentReportId_button',
    okDocumentReportPopupBtn: '#ebsContainerContent_documentReportId_popupLkp_lookupgrid_toolbar_item_4',
    okDataSourcePopupLkp: '#ebsContainerContent_dataSource_popupLkp_lookupgrid_toolbar_item_4',
    actionBtn: '#actionsButton',
    dataSourceLkpBtn: '#ebsContainerContent_dataSource_button',
    showReportBtn: '#showReport',
    deleteReportItemsBtn: '#ebsContainerContent_sys_reportitem_report_toolbar_item_2',
  },
  table: {
    firstTestRecord: locate('td').withText('Test Record 1'),
    firstRecordReportItems: locate('tr').withAttr({ 'aria-rowindex': '1' }).inside('#ebsContainerContent_sys_reportitem_report'),
    reportRecordFromTable: locate('td').withText('Test One').inside(locate('div').withAttr({ id: 'reportTableContainer' })),
    reportItemsContainerTable: '#ebsContainerContent_sys_reportitem_report',
    noDataReportItemsTable: locate('span').withText('No data').inside('#ebsContainerContent_sys_reportitem_report'),
  },
  labels: {
    editDocReportPageLabel: locate('span').withText('Edit AT_CreateDocReport').inside(locate('h5').withAttr({ id: 'modelType' })),
    editCustomReportPageLabel: locate('span').withText('Edit AT_CreateCustomReport').inside(locate('h5').withAttr({ id: 'modelType' })),
    reportLink: locate('a').withAttr({ id: 'ReportGroup0Btn' }),
    formTitleGridReport: locate('h5').withText('AT Simple Grid Report'),
    editReportItemPageLabel: locate('span').withText('Edit Report Item').inside(locate('h5').withAttr({ id: 'modelType' })),
    reportsListLabel: locate('h5').withText('Reports list').inside('#listViewContainerId'),
  },
  selector: {
    selectScopeEntityDD: locate('p').withText('Entity').inside('.dx-list-item'),
    selectScopeGeneralDD: locate('p').withText('General').inside('.dx-list-item'),
    selectTypeDocumentDD: locate('p').withText('Document').inside('.dx-list-item'),
    selectTypeCustomReportDD: locate('p').withText('Custom Report').inside('.dx-list-item'),
    selectTypeSimpleGridReportDD: locate('p').withText('Simple Grid Report').inside('.dx-list-item'),
    selectOutputAttachEntityDD: locate('p').withText('Attach to entity').inside('.dx-list-item'),
    selectReportDocumentTypeDD: locate('p').withText('PDF').inside('.dx-list-item'),
    selectReportOnScreenTypeDD: locate('p').withText('OnScreen').inside('.dx-list-item'),
  },
  checkbox: {
    isDefaultCheckbox: '#ebsContainerContent_isdefault',
  },
};
