module.exports = {
  fields: {
    inputNameField: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_Name'),
    inputTypeField: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_Type'),
    inputSearchByNameCASecurityRole: locate('input').withAttr({ type: 'text' }).inside(locate('td').withAttr({ 'aria-colindex': '2' })).inside('#ebsContainerContent_CustomActionSecurityRole_manyPopup_lookupgrid'),
    inputSearchByNameDashboardSR: locate('input').withAttr({ type: 'text' }).inside(locate('td').withAttr({ 'aria-colindex': '2' })).inside('#ebsContainerContent_DashboardSecurityRole_manyPopup_lookupgrid'),
    inputSearchByNameFormSectionSR: locate('input').withAttr({ type: 'text' }).inside(locate('td').withAttr({ 'aria-colindex': '2' })).inside('#ebsContainerContent_FormSectionSecurityRole_manyPopup_lookupgrid'),
    inputSearchByNameFormSR: locate('input').withAttr({ type: 'text' }).inside(locate('td').withAttr({ 'aria-colindex': '2' })).inside('#ebsContainerContent_EntityFormSecurityRole_manyPopup_lookupgrid'),
    inputLookupAttributeType: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_AT_LookupAttribute_Type'),
    inputSearchByName: locate('input').withAttr({ type: 'text' }).inside(locate('td').withAttr({ 'aria-colindex': '2' })).inside('#ebsContainerContent_CustomActionSecurityRole_manyPopup_lookupgrid'),
    searchByUsernameField: locate('input').withAttr({ type: 'text' }).inside(locate('td').withAttr({ 'aria-colindex': '2' })),
    emailInputField: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_email'),
    phoneNumberInputField: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_phoneNumber'),
    displayNameInputField: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_displayName'),
    userNameInputField: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_userName'),
    passwordInputField: locate('input').withAttr({ type: 'password' }).inside('#ebsContainerContent_password'),
    confirmPasswordInputField: locate('input').withAttr({ type: 'password' }).inside('#ebsContainerContent_confirmPassword'),
  },
  container: {
    defaultContainerContent: locate('div').withAttr({ id: 'ebsContainerContent' }),
  },
  buttons: {
    insertExistingCustomActionBtn: '#ebsContainerContent_CustomActionSecurityRole_toolbar_item_1',
    insertExistingDashboardBtn: '#ebsContainerContent_DashboardSecurityRole_toolbar_item_1',
    insertExistingFormSectionBtn: '#ebsContainerContent_FormSectionSecurityRole_toolbar_item_1',
    insertExistingFormBtn: '#ebsContainerContent_EntityFormSecurityRole_toolbar_item_1',
    okPopupSecRolesButton: '#ebsContainerContent_CustomActionSecurityRole_manyPopup_lookupgrid_toolbar_item_4',
    okPopupDashboardSecRolesBtn: '#ebsContainerContent_DashboardSecurityRole_manyPopup_lookupgrid_toolbar_item_4',
    okPopupFormSecSecRolesBtn: '#ebsContainerContent_FormSectionSecurityRole_manyPopup_lookupgrid_toolbar_item_4',
    okPopupFormSecRolesBtn: '#ebsContainerContent_EntityFormSecurityRole_manyPopup_lookupgrid_toolbar_item_4',
    okPopupLookupExtensionBtn: '#ebsContainerContent_AT_LookupAttribute_popupLkp_lookupgrid_toolbar_item_4',
    addLookupAttributeBtn: '#ebsContainerContent_AT_LookupAttribute_button',
    nextButton: locate('button').withText('Next'),
    finishButton: locate('button').withText('Finish'),
    dropdownArrowBusinessUnitButton: '#ebsContainerContent_businessUnitId_button',
    okButtonBusinessUnit: '#ebsContainerContent_businessUnitId_popupLkp_lookupgrid_toolbar_item_4',
    dropdowArrowSystemUserTypeButton: '#ebsContainerContent_systemUserTypeId_button',
    okButtonSystemUserType: '#ebsContainerContent_systemUserTypeId_popupLkp_lookupgrid_toolbar_item_4',
  },
  checkbox: {
    adminCheckBox: '#ebsContainerContent_isAdministrator',
    isAuthorizedCheckBox: '#ebsContainerContent_isAuthorized',
  },
  labels: {
    modelTypeLabel: locate('h5').withAttr({ id: 'modelType' }),
  },
  table: {
    tableAT_EntSecRoleEntExt_A: '#ebsContainerContent_AT_EntSecRoleEntExt_B_AT_LookupAttribute_AT_EntSecRoleEntExt_A',
    tableCustomActionSecurityRole: '#ebsContainerContent_CustomActionSecurityRole_manyPopup_lookupgrid',
    tableDashboardSecurityRole: '#ebsContainerContent_DashboardSecurityRole_manyPopup_lookupgrid',
    tableFormSectionSecurityRole: '#ebsContainerContent_FormSectionSecurityRole_manyPopup_lookupgrid',
    tableFormSecurityRole: '#ebsContainerContent_EntityFormSecurityRole_manyPopup_lookupgrid',
    tableAT_LookupAttribute: '#ebsContainerContent_AT_LookupAttribute_popupLkp_lookupgrid',
    firstTableRow: locate('tr').withAttr({ 'aria-rowindex': '1' }),
  },
  errors: {
    incorrectLogin: locate('span').withText('The username or password provided is incorrect.').inside(locate('div').withAttr({ id: 'card-login-colors' })),
    unauthorizedLogIn: locate('span').withText('Access is denied. User is unauthorized.').inside(locate('div').withAttr({ id: 'card-login-colors' })),
  },
};
