module.exports = {
  container: {
    defaultEntityContainer: locate('div').withAttr({ id: 'ebsContainerContent' }),
    defaultEntityFormFieldContainer: locate('div').withAttr({ id: 'ebsContainerContent_sys_entityformoptionfield_entityform_wrap' }),
    defaultEntityExtensionContainer: locate('div').withAttr({ id: 'ebsContainerContent_entityExtension_entity_default' }),
    relatedNameEntityExtension: locate('div').withAttr({ id: 'ebsContainerContent_virtualAttribute_entityExtension' }),
    relatedNameEntityFormExtension: locate('div').withAttr({ id: 'ebsContainerContent_virtualAttribute_entityExtension_fromEntityExtension' }),
  },
  fields: {
    customTooltipField: locate('textarea').withAttr({ class: 'dx-texteditor-input' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_customTooltip' })),
    attributeTooltipField: locate('textarea').withAttr({ role: 'textbox' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_tooltip' })),
    virtualAttributeField: locate('div').withText('Virtual Attribute'),
    inputNameViewField: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_Name' })),
    inputCodeTooltipField: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_Code' })),
    inputNameTooltipField: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ 'data-original-title': 'Tooltip-Attribute' })),
    inputValueTooltipField: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_Value' })),
    inputVARelatedAttributeField: locate('div').withAttr({ id: 'ebsContainerContent_AT_EntForRelatedVAId' }),
    inputNameVARelatedAttributeField: locate('div').withAttr({ id: 'ebsContainerContent_AT_EntForRelatedVAId_Name' }),
    inputTextVirtualTooltipField: locate('div').withAttr({ id: 'ebsContainerContent_TextVirtual' }),
    inputAddTextTooltipField: locate('textarea').withAttr({ role: 'textbox' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_tooltip' })),
  },
  table: {
    textVirtualDataTable: locate('td').withText('TextVirtual').inside(locate('.dx-datagrid-table-fixed')),
  },
  checkbox: {
    virtualAttributeCheckbox: locate('span').withAttr({ class: 'dx-checkbox-icon' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_useVirtualAttribute' })),
    showTooltipsOnFormsCheckbox: locate('input').withAttr({ id: 'showTooltipsOnForms' }),
    tooltipsOnFormsCheckbox: locate('i').withAttr({ class: 'helper' })
  },
  button: {
    insertButton: locate('div').withText('Insert'),
    insertFormFieldButton: locate('div').withAttr({ id: 'ebsContainerContent_sys_entityformoptionfield_entityform_toolbar_item_1' }),
    okLookupTableButton: locate('div').withAttr({ id: 'ebsContainerContent_attributeId_popupLkp_lookupgrid_toolbar_item_3' }),
    okVirtualAttributeButton: locate('div').withAttr({ id: 'ebsContainerContent_virtualAttributeId_popupLkp_lookupgrid_toolbar_item_3' }),
    insertTooltipButton: locate('i').withAttr({ class: 'sidebar-icons new' }).inside(locate('a').withAttr({ id: 'InsertBtn' })),
    tooltipsOnButton: locate('span').withText('Tooltips On'),
    toggleOnOFFTooltip: locate('label').withAttr({ for: 'formTooltipsToggleInput' }),
    saveShowTooltipsFormsButton: locate('span').withText('Save').inside(locate('.btn-ftosblue')),
    insertViewColumn: '#ebsContainerContent_sys_entityviewcolumn_entityview_toolbar_item_1',
    selectEntityViewInColumn: '#ebsContainerContent_entityViewId_button',
    ok: '#ebsContainerContent_entityViewId_popupLkp_lookupgrid_toolbar_item_4',
    generateColumnsButton: locate('button').withAttr({ id: 'btnGenerateColumns' }),
    insertNewRelFormParentViewButton: locate('div').withAttr({ id: 'ebsContainerContent_AT_RelFormChild_AT_RelFormParentId_AT_RelFormParent_toolbar_item_1' }),
    insertNewAT_InsIns1_AT_InsIns2Button: locate('div').withAttr({ id: 'ebsContainerContent_AT_InsIns1_AT_InsIns2_manyPopup_lookupgrid_toolbar_item_3' }),
    okPopupButton: locate('div').withAttr({ id: 'ebsContainerContent_AT_InsIns1_AT_InsIns2_manyPopup_lookupgrid_toolbar_item_4' }),
    okPopupNtoNButton: locate('div').withAttr({ id: 'ebsContainerContent_AT_InlineEditRel1_AT_InlineEditRel2_relationship_manyPopup_lookupgrid_toolbar_item_4' }),
    okPopupInlineEditingButton: locate('div').withAttr({ id: 'lookupedit_base_AT_ForInlineEditingCurrencyId_displayname_0_popupLkp_lookupgrid_toolbar_item_4' }),
    insertNewAT_InlineEditRel1Button: locate('div').withAttr({ id: 'ebsContainerContent_AT_InlineEditRel1_AT_InlineEditRel2_relationship_toolbar_item_1' }),
    saveInlineEditingButton: locate('a').withText('Save').inside('.dx-command-edit'),
    saveBatchViewButton: locate('i').withAttr({ class: 'dx-icon dx-icon-edit-button-save' }),
    saveButton: locate('a').withText('Save'),
    saveSpanButton: locate('span').withText('Save'),
    cancelButton: locate('span').withText('Cancel'),
    discardButton: locate('i').withAttr({ class: 'dx-icon dx-icon-edit-button-cancel' }),
    virtualAttributeTab: locate('span').withText('Virtual Attributes'),
  },
  selector: {
    selectFromShowTooltipDropdown: locate('div').withAttr({ class: 'dx-dropdowneditor-icon' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_showTooltipId_list' })),
    selectNoFromShowTooltipDropdown: locate('p').withText('No').inside('.dx-list-item-content'),
    selectVirtualAttributeDropdown: locate('i').withAttr({ class: 'dx-icon dx-icon-arrowdown' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_virtualAttributeId_button' })),
  },
};
