module.exports = {
  fields: {
    numericAttributeInputField: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_AT_UIDesigner_Numeric'),
    numericVAttributeInputField: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_AT_UIDesignerVA_Numeric'),
    desiredTextInputField: '//*[@id="main-page"]/body/div[6]/div/div[2]/div/div/div[2]/div[2]/div[2]/div[2]/div[1]/div/div[1]/div/div[1]/div[2]/div[2]/div[1]/div/div/div[1]/input',
    localizableTextInputField: '//*[@id="main-page"]/body/div[6]/div/div[2]/div/div/div[2]/div[2]/div[2]/div[2]/div[1]/div/div[1]/div/div[1]/div[2]/div[3]/div/div/div[1]/input',
    fillButtonTextInputField: locate('input').withAttr({ type: 'text' }).inside('#ebsUIDFormButtonBehaviourCollapsible').at(2),
    fillButtonIDInputField: '//*[@id="ebsUIDFormButtonBehaviourCollapsible"]/div[3]/div/div/div[1]/input',
    fillButtonIDField: '//*[@id="ebsUIDFormButtonBehaviourCollapsible"]/div[3]/div',
    formActionField: '#ftosUidFormActins_container_multiselect',
    formActionMessageInputField: locate('input').withAttr({ type: 'text' }).inside('#ebsUIDFormButtonBehaviourCollapsible').at(6),
    selectRelationInputField: '//*[@id="main-page"]/body/div[6]/div/div[2]/div/div/div[2]/div[2]/div[2]/div[8]/div[1]/div/div[1]/div/div[1]/div[2]/div[1]/div/div/div/div[2]/div[2]',
    selectAttributeDataFormField: '//*[@id="main-page"]/body/div[6]/div/div[2]/div/div/div[2]/div[2]/div[2]/div[4]/div[1]/div/div[1]/div/div[1]/div[2]/div[1]/div/div/div/div[2]/div[2]',
    selectRelationDataFormField: '//*[@id="main-page"]/body/div[6]/div/div[2]/div/div/div[2]/div[2]/div[2]/div[8]/div[1]/div/div[1]/div/div[1]/div[2]/div[1]/div',
    userIDInputField: locate('input').withAttr({ type: 'text' }).inside('#ebsContainerContent_userId'),
  },
  buttons: {
    uiDesignerButton: '#mceu_19-button',
    moveDownButton210Container: '//*[@id="main-page"]/body/div[6]/div/div[2]/div/div/div[2]/div[1]/div[1]/div/div[1]/div[2]/div/div/div[2]/div[3]/button[2]',
    moveUpButton210Container: '//*[@id="main-page"]/body/div[6]/div/div[2]/div/div/div[2]/div[1]/div[1]/div/div[1]/div[2]/div/div/div[3]/div[3]/button[1]',
    deleteButton210Container: '//*[@id="main-page"]/body/div[6]/div/div[2]/div/div/div[2]/div[1]/div[1]/div/div[1]/div[2]/div/div/div[3]/div[3]/button[3]',
    updateTemplateButton: locate('button').withText('Update template').inside(locate('div').withAttr({ role: 'toolbar' })),
    moveUpButtonLabelAttribute: '//*[@id="main-page"]/body/div[6]/div/div[2]/div/div/div[2]/div[1]/div[1]/div/div[1]/div[2]/div/div/div[4]/div[2]/button[1]',
    moveDownButtonLabelAttribute: '//*[@id="main-page"]/body/div[6]/div/div[2]/div/div/div[2]/div[1]/div[1]/div/div[1]/div[2]/div/div/div[3]/div[2]/button[2]',
    deleteButtonLabelAttribute: '//*[@id="main-page"]/body/div[6]/div/div[2]/div/div/div[2]/div[1]/div[1]/div/div[1]/div[2]/div/div/div[4]/div[2]/button[3]',
    dropdownButtonSelectAttribute: '//*[@id="main-page"]/body/div[6]/div/div[2]/div/div/div[2]/div[2]/div[2]/div[4]/div[1]/div/div[1]/div/div[1]/div[2]/div[1]/div/div[1]/div/div[2]/div[2]',
    dropdownButtonSelectVAttribute: '//*[@id="main-page"]/body/div[6]/div/div[2]/div/div/div[2]/div[2]/div[2]/div[6]/div[1]/div/div[1]/div/div[1]/div[2]/div[1]/div/div[1]/div/div[2]/div[2]',
    applyChangesAttributeButton: '//*[@id="main-page"]/body/div[6]/div/div[2]/div/div/div[2]/div[2]/div[2]/div[4]/div[2]/button',
    applyChangesButtonVA: '//*[@id="main-page"]/body/div[6]/div/div[2]/div/div/div[2]/div[2]/div[2]/div[6]/div[2]/button',
    applyChangesButtonHeading: '//*[@id="main-page"]/body/div[6]/div/div[2]/div/div/div[2]/div[2]/div[2]/div[2]/div[2]/button',
    applyChangesButtonChart: locate('button').withText('Apply changes').at(6),
    applyChangesButton: locate('button').withText('Apply changes').at(7),
    applyChangesRelationButton: locate('button').withText('Apply changes').at(8),
    applyChangesAttrDataFormButton: locate('button').withText('Apply changes').at(4),
    applyChangesRelationButtonDataForms: locate('button').withText('Apply changes').at(8),
    buttonUIDesigner: locate('button').withText('Button').inside(locate('div').withAttr({ class: 'container ftos-uid-html-holder' })),
    buttonTypeDropdownButton: '//*[@id="main-page"]/body/div[6]/div/div[2]/div/div/div[2]/div[2]/div[2]/div[7]/div[1]/div/div[1]/div/div[1]/div[2]/div[2]/div[1]/div/div/div/div[2]/div[2]',
    selectCustomProcessorDropdownButton: '//*[@id="ebsUIDFormButtonBehaviourCollapsible"]/div[5]/div/div[1]/div/div',
    selectColorDropdownButton: locate('div').withAttr({ role: 'button' }).inside('#ebsUIDFormButtonStyleCollapsible'),
    selectSizeDropdownButton: locate('div').withAttr({ class: 'dx-show-invalid-badge dx-selectbox dx-textbox dx-texteditor dx-dropdowneditor-button-visible dx-editor-outlined dx-widget dx-dropdowneditor dx-dropdowneditor-field-clickable' }).inside('#ebsUIDFormButtonStyleCollapsible').at(2),
    selectIconDropdownButton: locate('div').withAttr({ class: 'dx-show-invalid-badge dx-selectbox dx-textbox dx-texteditor dx-dropdowneditor-button-visible dx-editor-outlined dx-widget dx-dropdowneditor dx-dropdowneditor-field-clickable' }).inside('#ebsUIDFormButtonStyleCollapsible').last(),
    checkoutButton: '#templateCheckOutButtonId',
  },
  selector: {
    headingUIDesigner: locate('div').withAttr({ 'data-template-id': 'heading' }).inside(locate('div').withAttr({ class: 'container ftos-uid-html-holder' })),
    testHeading: locate('div').withAttr({ class: 'h3-regular-os text-center' }),
    chartUIDesigner: locate('div').withAttr({ 'data-template-id': 'chart' }).inside(locate('div').withAttr({ class: 'container ftos-uid-html-holder' })),
    optionDropdown: locate('div').withAttr({ role: 'option' }),
    relationshipTypeUIDesigner: locate('div').withAttr({ 'data-component-type': 'relationship' }).inside(locate('div').withAttr({ class: 'container ftos-uid-html-holder' })),
    attributeContainerDataForm: locate('div').withAttr({ 'data-component-type': 'attribute' }).inside(locate('div').withAttr({ class: 'container ftos-uid-html-holder' })),
    relationshipTypeDataForm: locate('div').withAttr({ 'data-component-type': 'relationship' }).inside(locate('div').withAttr({ class: 'container ftos-uid-html-holder' })),
    relationshipContainer: locate('div').withAttr({ 'data-template-id': 'relationship' }),
    htmlEditorIFrame: '#ebsContainerContent_template_ifr',
    headingTypeDropdown: '//*[@id="main-page"]/body/div[6]/div/div[2]/div/div/div[2]/div[2]/div[2]/div[2]/div[1]/div/div[1]/div/div[1]/div[2]/div[1]/div/div[1]/div/div[2]/div[2]',
    textAlignmentDropdown: '//*[@id="main-page"]/body/div[6]/div/div[2]/div/div/div[2]/div[2]/div[2]/div[2]/div[1]/div/div[1]/div/div[1]/div[2]/div[4]/div/div[1]/div/div[2]/div[2]',
    selectChartDropdown: '//*[@id="main-page"]/body/div[6]/div/div[2]/div/div/div[2]/div[2]/div[2]/div[6]/div[1]/div/div[1]/div/div[1]/div[2]/div/div/div/div/div[1]/input',
  },
  containers: {
    container12: '//*[@id="ebsContaininersCollapsible"]/div[1]',
    container2and10: '//*[@id="main-page"]/body/div[6]/div/div[2]/div/div/div[2]/div[1]/div[1]/div/div[1]/div[2]/div/div/div[3]',
    container12HTMLEditor: '//*[@id="tinymce"]/div[2]',
    container3and9HTMLEditor: '//*[@id="tinymce"]/div[3]',
    container4and8HTMLEditor: '//*[@id="tinymce"]/div[4]',
    container6and6HTMLEditor: '//*[@id="tinymce"]/div[5]',
    container8and4HTMLEditor: '//*[@id="tinymce"]/div[6]',
    container9and3HTMLEditor: '//*[@id="tinymce"]/div[7]',
    container10and2HTMLEditor: '//*[@id="tinymce"]/div[8]',
    container4x3HTMLEditor: '//*[@id="tinymce"]/div[9]',
    container3x4HTMLEditor: '//*[@id="tinymce"]/div[10]',
    container12Portal: '//*[@id="ebsContainerContent"]/div/div/div/div/div[2]/div',
    container3and9Portal: '//*[@id="ebsContainerContent"]/div/div/div/div/div[3]',
    container4and8Portal: '//*[@id="ebsContainerContent"]/div/div/div/div/div[4]',
    container6and6Portal: '//*[@id="ebsContainerContent"]/div/div/div/div/div[5]',
    container8and4Portal: '//*[@id="ebsContainerContent"]/div/div/div/div/div[6]',
    container9and3Portal: '//*[@id="ebsContainerContent"]/div/div/div/div/div[7]',
    container10and2Portal: '//*[@id="ebsContainerContent"]/div/div/div/div/div[8]',
    container4x3Portal: '//*[@id="ebsContainerContent"]/div/div/div/div/div[9]',
    container3x4Portal: '//*[@id="ebsContainerContent"]/div/div/div/div/div[10]',
    scrollableContainer: locate('div').withAttr({ class: 'dx-scrollable-content' }),
    container: '#ebsContainerContent',
    htmlHolderContainer: locate('div').withAttr({ class: 'container ftos-uid-html-holder' }),
    htmlContainer: '#tinymce',
  },
  dataTemplates: {
    firstLabelAttributeTemplatePortal: '//*[@id="ebsContainerContent"]/div/div/div/div/div[2]/div[1]',
    secondLabelAttributeTemplatePortal: '//*[@id="ebsContainerContent"]/div/div/div/div/div[2]/div[2]/div',
    thirdLabelAttributeTemplatePortal: '//*[@id="ebsContainerContent"]/div/div/div/div/div[3]',
    firstLabelAttributeTemplateHTMLEditor: '//*[@id="tinymce"]/div[2]/div[1]/div',
    secondLabelAttributeTemplateHTMLEditor: '//*[@id="tinymce"]/div[2]/div[2]/div',
    thirdLabelAttributeTemplateHTMLEditor: '//*[@id="tinymce"]/div[3]',
    forthLabelAttributeTemplate: '//*[@id="main-page"]/body/div[6]/div/div[2]/div/div/div[2]/div[1]/div[1]/div/div[1]/div[2]/div/div/div[4]',
    labelAttrSelectLA: locate('div').withAttr({ 'data-template-id': 'row' }).inside(locate('div').withAttr({ class: 'container ftos-uid-html-holder' })),
    labelAttrSelectLAHTMLEditor: locate('div').withAttr({ 'data-template-id': 'row' }).inside('#tinymce'),
  },
  checkboxes: {
    roundStyleButtonCheckbox: locate('span').withText('Round').inside('#ebsUIDFormButtonStyleCollapsible'),
    filledStyleButtonCheckbox: locate('span').withText('Filled').inside('#ebsUIDFormButtonStyleCollapsible'),
    customFormActionCheckbox: locate('div').withText('CustomFormAction').inside(locate('div').withAttr({ class: 'dx-scrollview-content' })),
    noInsertCheckbox: locate('span').withText('No Insert').inside(locate('div').withAttr({ role: 'checkbox' })),
  },
  tabs: {
    uiTab: locate('span').withText('UI').inside('#stepper'),
  },
};
