// Data
const data = require('~data/userJourney/userJourneyData');
const createHeaderData = require('~data/userJourney/userJourneyCreateHeader');

module.exports = {
  fields: {
    ujInput1: locate('input').inside(locate('div').withAttr({ id: 'ebsContainerContent_name' })),
    ujInput2: locate('input').inside(locate('div').withAttr({ id: 'ebsContainerContent_displayName' })),
    ujInput3: locate('input').inside(locate('div').withAttr({ id: 'ebsContainerContent_externalUrl' })),
    ujInput4: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_type_list' })),
    ujInput5: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_customActionId_dropDownBox' })),
    ujInput6: locate('input').inside(locate('div').withAttr({ id: 'ebsContainerContent_displayName' })),
    portalUjInputName: locate('input').inside(locate('div').withAttr({ id: 'ebsContainerContent_Name' })),
    ujFieldLabelInput: locate('input').inside(locate('div').withAttr({ id: 'ebsContainerContent_label' })),
    ujHeaderFormStepTwo: locate('input').inside(locate('div').withAttr({ id: 'ebsContainerContent_Code' })),
    ujHeaderAttrTypeValue: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_Value' })),
    ujHeaderAttrTypeHeaderOS: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_HeaderOS_list' })),
    ujHeaderAttrTypeDate: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_RegDate' })),
    ujHeaderLookupTableButton: '#ebsContainerContent_AT_EntForLkpHeaderId_button',
    searchForUserJourneyField: 'div#ftosFormJourneysHolder > div > div:nth-of-type(5) > div > table > tbody > tr:nth-of-type(2) > td:nth-of-type(2) > div > div:nth-of-type(2) > div > div > div > input',
    tableRowValueUserJourneyField: 'div#ftosFormJourneysHolder > div > div:nth-of-type(6) > div > table > tbody > tr > td:nth-of-type(2)',
    resultForNoData: '.dx-datagrid-nodata',
    nameInputUserJourneyField: locate('input').inside(locate('div').withAttr({ id: 'ebsContainerContent_name' })),
    nameInputUserJourneyField2: locate('input').inside(locate('div').withAttr({ id: 'ebsContainerContent_Name' })),
    displayNameInputUserJourneyField: locate('input').inside(locate('div').withAttr({ id: 'ebsContainerContent_displayName' })),
    dataModelUserJourneyTab: locate('span').withText('Data Model').inside(locate('div').withAttr({ id: 'stepper' })),
    generalUserJourneyTab: locate('span').withText('General').inside(locate('div').withAttr({ id: 'stepper' })),
    uiUserJourneyTab: 'div#stepper > div > div:nth-of-type(2) > span',
    stepsUserJourneyTab: 'div#stepper > div > div:nth-of-type(4) > span',
    searchForBusinessEntityExtentionField: 'div#ebsContainerContent_entityid_popupLkp_lookupgrid > div > div:nth-of-type(5) > div > table > tbody > tr:nth-of-type(2) > td > div > div:nth-of-type(2) > div > div > div > input',
    selectFirstRecordFromTableEntityExtentionPopup: 'div#ebsContainerContent_entityid_popupLkp_lookupgrid > div > div:nth-of-type(6) > div > div > div > div > table > tbody > tr > td',
    firstAttributeCodeField: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_Code' })),
    secondAttributeDateDobField: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_DoB' })),
    firstAttributeNameField: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_Name' })),
    secondAttributeValueField: locate('input').withAttr({ type: 'text' }).inside(locate('div').withAttr({ id: 'ebsContainerContent_Value' })),
    firstParagraphField: 'div#ew-controllers > div > ul > li > p',
    secondParagraphField: 'div#ew-controllers > div > ul > li:nth-of-type(2) > p',
    wizardOptionTabMonacoField: 'div#ebsContainerContent_wizardOptionsmonaco > div > div > div:nth-of-type(2) > div > div:nth-of-type(4) > div',
    fetchObjectExpression: 'div#ebsContainerContent_fetchObjectExpressionmonaco > div > div > div:nth-of-type(2) > div > div:nth-of-type(4) > div',
    userJourneyFormNameField: 'h5#modelType > span',
    displayOptionsViewField: 'div#ebsContainerContent_displayOptionsmonaco > div > div > div:nth-of-type(2) > div > div:nth-of-type(4) > div',
    displayJavaScriptMonacoField: 'div#ebsContainerContent_Javascriptmonaco > div > div > div:nth-of-type(2) > div > div:nth-of-type(4) > div',
    inputSearchInCUJTableField: locate('input').withAttr({ type: 'text' }).inside(locate('td').withAttr({ 'aria-colindex': '2' })),
    searchFieldUserJourney: locate('input').withAttr({ type: 'text' }).inside(locate('td').withAttr({ 'aria-colindex': '2' })),
    searchFDFNameFlowDJ: locate('input').withAttr({ type: 'text' }).inside(locate('td').withAttr({ 'aria-colindex': '1' })),
    firstRowJsField: locate('span').withText('&nbsp;').inside(locate('div').withAttr({ class: 'view-line' })),
    selectFDFField: '#ebsContainerContent_formDrivenFlowId_dropDownBox',
  },
  buttons: {
    createButton: locate('button').withAttr({ id: 'createStandardUJBtn' }),
    deleteButton: locate('button').withAttr({ id: 'deleteCustomUJBtn' }),
    insertButton: locate('button').withAttr({ id: 'InsertBtn' }),
    entityExtentionArrowDown: locate('div').withAttr({ id: 'ebsContainerContent_entityid_button' }),
    nextWizardButton: '//*[@id="ebsContainerContent"]/div[5]/div[1]/button[2]',
    okUserJourneyButton: '#ebsContainerContent_entityid_popupLkp_lookupgrid_toolbar_item_4',
    historyAfterGenerateJsButton: '#ebsContainerContent_afterGenerateJs_sc_history_button',
    historyTemplateButton: '#ebsContainerContent_template_history_history_button',
    detailsDJButton: locate('div').withAttr({ title: 'Details' }).inside(locate('#fmRightButtonsHolder')),
    deleteDJButon: locate('div').withAttr({ title: 'Delete' }).inside(locate('#fmRightButtonsHolder')),
    addFlowDJ: '#fmLeftButtonsHolder',
    checkoutButton: '#templateCheckOutButtonId',
  },
  tabs: {
    firstSectionParagraph: 'div#stepper > div > div > span',
    secondSectionParagraph: 'div#stepper > div > div:nth-of-type(2) > span',
    thirdSectionParagraph: 'div#stepper > div > div:nth-of-type(3) > span',
    digitalJourneyMap: locate('span').withText('Digital Journey Map').inside(locate('div').withAttr({ id: 'stepper' })),
    wizardOptionsTab: locate('a').withAttr({ id: 'ui-id-3' }).withText('Wizard Options'),
  },
  properties: {
    readonlyProperties: '.ebs-readonly',
    mandatoryProperties: '.ebs-required',
    checkedProperties: '.dx-checkbox-checked',
    isNotEditable: '.dx-cell-focus-disabled',
  },
  labels: {
    customActionTitlePortalUJTBU: locate('h5').withAttr({ id: 'customActionTitle' }).withText('AT_CustomUJ_TBU123'),
    customFormPortalUJTBU: locate('div').withAttr({ id: 'ebsContainerContent' }).withText('Auto Test123'),
  },
  popup: {
    popupContent: '.dx-popup-content',
  },
  messagePopup: {
    successMessage: '.jq-icon-success',
    errorMessage: '.jq-icon-error',
  },
  selector: {
    ujCustomUjTable: locate('div').withAttr({ id: 'ftosCustomJourneysHolder' }),
    ujFormUjTable: locate('div').withAttr({ id: 'ftosFormJourneysHolder' }),
    ujMenuItemsTable: '#ebsContainerContent',
    ujOptionSet1: { title: data.ujAttribData4 },
    ujCodeTemplateTinyMceId: 'ebsContainerContent_template',
    ujCodeTemplateLoc: '#efSectionCodeTemplate div div div iframe',
    ujHtmlCodeIFrame: '#ebsContainerContent_template_ifr',
    ujHtmlBody: locate('body').withAttr({ id: 'tinymce' }),
    ujAfterGenerateJsMonacoId: 0,
    ujAfterGenerateJsLoc: '#efSectionCodeAfterJs div div div div div',
    ujFieldAttributeLookupTableButton: '#ebsContainerContent_attributeId_button',
    ujHeaderItemsTable: '#ebsContainerContent_entityformheaderitem_entityform',
    ujHeaderEmpty: locate('#ebsContainer div .opaque'),
    ujHeaderRowName: locate('h5').withText(createHeaderData.ujInputLabelValue2),
    ujHeaderRowNameVal: locate('span').withText(createHeaderData.ujHeaderFormNameValue),
    ujHeaderRowCode: locate('h5').withText(createHeaderData.ujInputLabelValue),
    ujHeaderRowCodeVal: locate('span').withText(createHeaderData.ujHeaderFormCodeValue),
    ujEditedHeader1: '#ebsContainer div div div div .header-items-holder .data-element:nth-child(1)',
    ujEditedHeader2: '#ebsContainer div div div div .header-items-holder .data-element:nth-child(2)',
    ujEditedHeader3: '#ebsContainer div div div div .header-items-holder .data-element:nth-child(3)',
    ujEditedHeaderPageBottom: '#ebsContainer div div p:last-child',
    ujAttributeLookupTable: locate('div').withAttr({ id: 'ebsContainerContent_attributeId_popupLkp_lookupgrid' }),
    ujLookupLookupTable: locate('div').withAttr({ id: 'ebsContainerContent_AT_EntForLkpHeaderId_popupLkp_lookupgrid' }),
    codeTemplateLoc: locate('iframe').withAttr({ id: 'ebsContainerContent_template_ifr' }),
  },
  checkbox: {
    ujIsPrimaryAttribute: '#ebsContainerContent_isPrimaryAttribute',
    ujStickyHeaderItems: '#ebsContainerContent_stickyHeaderItems',
    selectTheCheckbox: '.dx-select-checkbox.dx-datagrid-checkbox-size.dx-checkbox',
    selectSingleResultCheckbox: '.dx-command-select',
    selectSingleResultCheckedCheckbox: 'dx-checkbox-icon marked-element',
    isDefault: '#ebsContainerContent_isdefault',
    isDefaultForEdit: '#ebsContainerContent_isdefaultEdit',
    wizardModeCheckbox: 'div#ebsContainerContent_wizardMode > div > span',
    renderSectionTabsCheckbox: 'div#ebsContainerContent_renderTabsAsBullets > div > span',
  },
  container: {
    containerContent: '#ebsContainerContent',
    containerEwContent: '#ew-container',
    stepsTableContainer: '#ebsContainerContent_sys_entityformsection_entityform',
    formJourneyCustomactionTableContainer: '#ebsContainerContent_sys_entityformsection_entityform',
  },
};
