name: Automated Tests Workflow
on: workflow_dispatch

env:
  GITHUB_SHA: ${{ github.sha }}
  ARCHIVE: FTOS

jobs:
  build:
    runs-on: windows-latest
    name: Node ${{ matrix.node }} sample
    steps:
      - uses: actions/checkout@v2
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npm run test
